### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Jhovany200** [Klocman/Bulk-Crap-Uninstaller#101]
I was asked if I could put the cmd window or processes running BCUninstaller in hidden or minimized, when uninstall.
Only if you can.

Take it as a suggestion, so that it looks better.

**Comment by Klocman** [comment]
Do you mean the uninstall windows? I already have plans to hide at least some of them, but it's difficult so it's taking a while.

**Comment by Jhovany200** [comment]
![captura](https://user-images.githubusercontent.com/30766228/29849392-8f45f264-8cf4-11e7-8fdf-8531d53e9f65.jpg)
Only if you can put it in hidden mode. But still working as usual.

Just a suggestion, do not take it as something mandatory.

**Comment by Klocman** [comment]
This is exactly what #88 is about. It's a temporary interface useful for debugging that I was too lazy to change :)

**Comment by Jhovany200** [comment]
Ok, thanks for your attention, very good software.
