### ISSUE TITLE
Add uninstall helper for simple delete instead of using cmd

### ISSUE THREAD

**Issue by Klocman** [Klocman/Bulk-Crap-Uninstaller#102]
Give it a progress bar, and option to run loud (maybe no ui at all for quiet). Loud has uninstall/cancel question, and maybe a tree of files to check what to delete.

**Comment by Jhovany200** [comment]
![captura](https://user-images.githubusercontent.com/30766228/29849512-4dbb084c-8cf5-11e7-901b-4a359f7676b2.jpg)
Only if you can put it in hidden mode. But still working as usual.

Just a suggestion, do not take it as something mandatory.
