### ISSUE TITLE
github pages

### ISSUE THREAD

**Issue by Jhovany200** [Klocman/Bulk-Crap-Uninstaller#103]
I've also wondered if you can create a web page with github for BCUninstaller, and do it in several languages, obviously we all collaborate with your translation.

it's just a suggestion.

"github pages"

**Comment by Klocman** [comment]
I'll look into it. If anything, I could put the contents of the help file here.

**Comment by Klocman** [comment]
For now I added the help file to the wiki. There's no plans for a Pages webpage.
