### ISSUE TITLE
Windows App Paint3D leftovers

### ISSUE THREAD

**Issue by DmitriyYukhanov** [Klocman/Bulk-Crap-Uninstaller#111]
Hey, I've noticed these leftovers left unnoticed after Paint3D App removal:

HKEY_CURRENT_USER\Software\Classes\Local Settings\MrtCache\C:%5CProgram Files%5CWindowsApps%5CMicrosoft.MSPaint_3.1709.5027.0_x64__8wekyb3d8bbwe%5Cresources.pri

HKEY_CURRENT_USER\Software\Microsoft\UserData\UninstallTimes
With binary value
Microsoft.MSPaint_8wekyb3d8bbwe

**Comment by Klocman** [comment]
I've looked into these, and I think it's better not to delete them. It might cause problems with reinstalling the applications and installing new ones.
