### ISSUE TITLE
Refresh process hangs when main window is minimized

### ISSUE THREAD

**Issue by DmitriyYukhanov** [Klocman/Bulk-Crap-Uninstaller#112]
Steps to reproduce:
- run BCU or select File > Reload uninstallers
- while reload in progress, minimize BCU window
- wait for a while until reload finishes
- restore BCU window
- see this forever:

![image](https://user-images.githubusercontent.com/883587/30403519-b2ae4538-98ea-11e7-8ab1-70ebf5108a3b.png)

**Comment by Klocman** [comment]
Confirmed, thank you for the bug reports!
