### ISSUE TITLE
Missing sources (or DLLs).  Klocman.Tools and UpdateSystem projects

### ISSUE THREAD

**Issue by botmtl** [Klocman/Bulk-Crap-Uninstaller#113]
Could you provide the source for KlocmanTools and UpdateSystem projects as well (see https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/master/source/BulkCrapUninstaller.sln for reference)?  The project cannot be built with the source provided here.

(If you want to keep KlocmanTools and UpdateSystem projects under licence and not provide the code, that's fine too, But could you then make a release dll for those projects so that we can link to them and build Bulk Crap Uninstaller?)

**Comment by Klocman** [comment]
Here you go.
https://github.com/Klocman/UpdateSystem
https://sourceforge.net/projects/kloctoolslibrary/
