### ISSUE TITLE
Add functions,  it's just a suggestion.

### ISSUE THREAD

**Issue by Jhovany200** [Klocman/Bulk-Crap-Uninstaller#116]
![anadir](https://user-images.githubusercontent.com/30766228/30576303-f1c66474-9cd4-11e7-810a-5ce28e6f049c.jpg)

if you could directly add the functions shown in the image to Bulk Crap Uninstaller.

if we completely replace the default uninstallation in Windows, as they will be all Windows functions and many already have Bulk Crap Uninstaller.

it's just a suggestion.

**Comment by Klocman** [comment]
Clicking Change runs the modify command, Repair seems to be the same command, I'm not sure what's the difference.

It's a good suggestion, BCU already captures the modify command and you can see it in properties. It will be restricted to a single application at a time though. The bulk system is focused on uninstalling and would require many changes to modify/repair instead.

**Comment by Jhovany200** [comment]
if you can put it in the main menu of Bulk Crap Uninstaller, only when it is selected 1 item

**Comment by Klocman** [comment]
Should I put it in the right click menu? I don't think it's going to be used often.

**Comment by Jhovany200** [comment]
but I would recommend it in the 2 places, only it is displayed when an item is selected, and when this multiple selected is hidden.

**Comment by TPS** [comment]
>Clicking Change runs the modify command, Repair seems to be the same command, I'm not sure what's the difference.

FWIW, ___if the installation was configured properly by the dev___, Repair seems to automatically rerun the last installation done w/ the same options, but no other prompts.  Modify prompts to let 1 change what was installed, & sometimes will even allow certain options not exposed via regular Install (& vice versa).

Typically, there aren't enough options w/ most software to make this worthwhile, so they often act the same.  1 can see this behavior most consistently via any of the large Office programs (Libre, Open, MS, &c).

**Comment by Klocman** [comment]
Thank you for the info @TPS. I added a modify option to the menu and the toolbar.
