### ISSUE TITLE
the correct thing would be to change the name to "reference colors", it's just a suggestion

### ISSUE THREAD

**Issue by Jhovany200** [Klocman/Bulk-Crap-Uninstaller#117]
![corregir](https://user-images.githubusercontent.com/30766228/30576749-e2cbf80a-9cd7-11e7-85fa-dbbc13d22d86.jpg)

the correct thing would be to change the name to "reference colors".

so the other people who translate including me, will change that part of the translation.

it's just a suggestion.

**Comment by Klocman** [comment]
I'm not sure about it, maybe "Color reference"?

"Color legend" means the same thing, and I think that it sounds more natural.

**Comment by Jhovany200** [comment]
OK, thanks for answering.
