### ISSUE TITLE
StoreAppHelper doesn't seem to be doing anything? (x64 Portable)

### ISSUE THREAD

**Issue by Lady-Luck** [Klocman/Bulk-Crap-Uninstaller#121]
I noticed that the program itself was not listing any Windows Store Apps whatsoever, the filter was on but it was grayed out.

So I opened the documentation and found that StoreAppHelper has a /query function, so I thought I'd try that and see if I could find the root cause of this.

I opened a command prompt and typed StoreAppHelper /query and hit Enter. Nothing seems to happen, at all.

**Comment by Klocman** [comment]
What version of Windows are you running? It should list installed apps and exit like on the screenshot (doesn't matter how you run it). BCU is using this helper to get the apps, so that's why it's not showing any.

![capture](https://user-images.githubusercontent.com/14913904/30774491-70962c74-a083-11e7-8810-75cfae6f0da5.PNG)

 Look for any crash dump files for the StoreAppHelper, they might be in WER\ReportArchive (usually in "C:\ProgramData\Microsoft\Windows\WER\ReportArchive"), you can also look for files starting with "AppCrash_StoreAppHelper"

**Comment by Lady-Luck** [comment]
I cleared my crash logs with disk cleanup before trying another test run, absolutely no crash logs in C:\ProgramData\Microsoft\Windows\WER

This is an insider build so that's probably why. Windows 10 x64 v1709 Build 16288.1

**Comment by Klocman** [comment]
I tested BCU on latest insider build and store apps loaded correctly. Can you check if other applications can see the store apps?

**Comment by Lady-Luck** [comment]
I got into the Skip Ahead program and I'm on Redstone 4 now. I tried the latest version and tried the steps I described above and I still can't get Windows Store apps to show up. It's unfortunate I was not able to test the new version on Redstone 3 before the update happened.

For what it's worth, if you're personally interested, there's a way to upgrade to this Insider build through a 'cheat': https://www.deskmodder.de/blog/2017/08/05/windows-10-insider-rs4-skip-ahead-wieder-aktivieren-in-den-einstellungen/

As for your other question, on Redstone 4, I downloaded the demo to Total Uninstall and it is able to see all the Windows Store apps, so it seems the problem is only with BCU.

**Comment by Klocman** [comment]
Can you try running this version? It should produce a .log file with the error.
[Debug.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/1360501/Debug.zip)

**Comment by Lady-Luck** [comment]
--- 10/6/2017 10:00:30 AM
System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at StoreAppHelper.AppManager.<>c.<QueryApps>b__1_0(Package package)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at StoreAppHelper.Program.Main(String[] args)

**Comment by Klocman** [comment]
I see, system's PackageManager is throwing in an unexpected location. Can you check if this version works for you? [Debug.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/1363356/Debug.zip)

**Comment by Lady-Luck** [comment]
I should really turn my email alerts back on.

That version works, yes.

**Comment by Klocman** [comment]
Alright, glad to hear that! You can use it with latest BCU release to see store apps until I release a new one.
