### ISSUE TITLE
Blurry fonts when using Windows Scale

### ISSUE THREAD

**Issue by DmitriyYukhanov** [Klocman/Bulk-Crap-Uninstaller#128]
Hey, when I set scale in Windows Settings to the 125%, I can see most fonts in BCU are blurry, like here (note the window caption text is not blurry):

![image](https://user-images.githubusercontent.com/883587/31361664-03fc3e1e-ad5d-11e7-996b-86202b876988.png)

**Comment by Klocman** [comment]
This is a known issue. Until BCU moves to .Net framework newer than 3.5 there's realistically nothing to be done about it.

**Comment by DmitriyYukhanov** [comment]
Thanks for looking into it.
Are there any plans on updating to the .NET 3.5+ ?
