### ISSUE TITLE
TeraCopy uninstallation leftovers / Classes\CLSID GUID detection and scanning for it in other locations

### ISSUE THREAD

**Issue by DmitriyYukhanov** [Klocman/Bulk-Crap-Uninstaller#130]
Hey, I've noticed few items wasn't detected as leftovers after [TeraCopy](http://www.codesector.com/teracopy) uninstallation:

Folder:
C:\Users\focus\AppData\Roaming\TeraCopy

Registry keys:
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{A7005AF0-D6E8-48AF-8DFA-023B1CF660A7}
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{A7645AF0-D6E8-48AF-8DFA-023B1CF660A7}
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{A7005AF0-D6E8-48AF-8DFA-023B1CF660A7}
(they all had nested key InProcServer32 with string value - path to the TeraCopy.dll and TeraCopy64.dll)

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\background\shellex\ContextMenuHandlers\TeraCopy
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\InternetShortcut\ShellEx\ContextMenuHandlers\TeraCopy
HKEY_CURRENT_USER\Software\Code Sector
HKEY_USERS\S-1-5-21-1278579218-726299998-186589410-1001\Software\Code Sector

Registry values:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved
{A7005AF0-D6E8-48AF-8DFA-023B1CF660A7} - TeraCopy
{A7645AF0-D6E8-48AF-8DFA-023B1CF660A7} - TeraCopy64

HKEY_USERS\S-1-5-21-1278579218-726299998-186589410-1001\Software\Microsoft\Windows\CurrentVersion\Explorer\UserAssist\{F4E57C4B-2036-45F0-A9AB-443BCFE33D9F}\Count
P:\CebtenzQngn\Zvpebfbsg\Jvaqbjf\Fgneg Zrah\GrenPbcl.yax - Binary Value

Thanks for keeping good work on your tool!

**Comment by Klocman** [comment]
It looks like everything is being picked up by now so I'll close the issue.

**Comment by garry-ut99** [comment]
By the way  - my story: On Windows 7 SP1 64bit I couldn't uninstall TeraCopy from system by its normal deinstalator: it was keeping throwing some running-service-lock error, nothing was helping: neither restarting system, nor restarting system in safe mode, nor disabling running TeraCopy service via service manager, nor using other uninstall tools,  TeraCopy was just stuck with no way to remove it. Then I tried Bulk-Crap-Uninstaller and it removed it easily. So definately Bulk-Crap-Uninstaller is useful.
