### ISSUE TITLE
Just add .NET v4 next to v2/3.5 support with one line (nothing has to change)

### ISSUE THREAD

**Issue by ltGuillaume** [Klocman/Bulk-Crap-Uninstaller#132]
Installing crap to uninstall crap is not the way to go.

A simple line
`<supportedRuntime version="v4.0"/>`
below the existing
`<supportedRuntime version="v2.0.50727"/>`
in BCUninstaller.exe.config is enough to keep people from having to install an entire .NET framework on Windows 8/10.

**Comment by Klocman** [comment]
Thank you, tested BCU on 4.0 and it works fine. I didn't know it would be this easy!

**Comment by ltGuillaume** [comment]
You're welcome :) Thanks for an awesome tool!
