### ISSUE TITLE
Junk scan offers to delete \AppData\Roaming\ 

### ISSUE THREAD

**Issue by Klocman** [Klocman/Bulk-Crap-Uninstaller#133]
> 3.17.0.32958 x64 seems to have an issue in cleaning up:
> 
> rather than highlight the appdata folder specific to the application, it offers to delete the entire appdata folder
> 
> e.g.
> instead of offering to delete
> 
> C:\Users\xxx\AppData\Roaming\Launchy
> 
> it offered to delete
> 
> C:\Users\xxx\AppData\Roaming\ 

Bug reproduced, to be fixed.

**Comment by Lady-Luck** [comment]
y i k e s

**Comment by Klocman** [comment]
> y i k e s

Thankfully it's got at most questionable confidence, so the user would need to manually select it.
