### ISSUE TITLE
Cannot open Uninstall Lists

### ISSUE THREAD

**Issue by SecareLupus** [Klocman/Bulk-Crap-Uninstaller#136]
After exporting an uninstall list (an XML, the only provided option), I tried to re-open the file, and it wouldn't show up in any of the open file dialogues. I could go into the folder, but no files were listed. The filetype filter dropdown only had the "Uninstall Lists" option available, so that was checked.

Is it possible that the filetype filter is expecting a file extension other than ".xml"?

**Comment by Klocman** [comment]
Are you using the newest version? The uninstall list should be saved in a .bcul file. You go to advanced filtering, set up your filters, and click on the save icon on the toolbar.
