### ISSUE TITLE
Allow BCU to remember where to store registry backups

### ISSUE THREAD

**Issue by cornytrace** [Klocman/Bulk-Crap-Uninstaller#140]
It would be nice that we can check the "Remember choice" checkmark when choosing a backup location for the registry, and that all backups are automatically put there from then on.

**Comment by Klocman** [comment]
Sounds like a good idea, considering how bad the folder select dialog is. Simply checking "Remember", Create, and selecting a directory is probably the best way of doing this, with an extra option in the settings.
