### ISSUE TITLE
Detect MSI dependencies to uninstall in correct order

### ISSUE THREAD

**Issue by cornytrace** [Klocman/Bulk-Crap-Uninstaller#141]
If at all possible, detect programs which depend on the MSI package which is going to be uninstalled, offer to uninstall all those programs/packages too, and uninstall them in the correct order.

**Comment by Klocman** [comment]
Good idea, it sounds doable, and might be expanded to all uninstaller types.

Did you do any research/thinking on how to do it?

**Comment by Klocman** [comment]
Turns out it's difficult to tell what is depending on what, this might not be doable without a lot of work and disk grinding.

For now I've added a new uninstall step that scans for related applications and offers to uninstall them as well.
