### ISSUE TITLE
Fail to uninstall Droid4X simulator for pc

### ISSUE THREAD

**Issue by johnsmith45213** [Klocman/Bulk-Crap-Uninstaller#147]
I did some testing and realized difficulties to uninstall PC simulators

**Comment by Klocman** [comment]
Do you still have it installed? If yes. in BCU select Droid4X, click File>Export selection, and upload the resulting file here.

**Comment by johnsmith45213** [comment]
https://rutube.ru/video/private/a16f1787d114825572487259df2f2cdb/?p=tzh-dQfzYy_ev9G4gh3hrg

**Comment by johnsmith45213** [comment]
<?xml version="1.0"?>
<ApplicationEntrySerializer xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Items>
    <ApplicationUninstallerEntry>
      <DisplayName>DuOS</DisplayName>
      <BundleProviderKey>25e5b76a-ca64-4569-b639-0f50cf4fb537</BundleProviderKey>
      <DisplayIcon>C:\Windows\Installer\{25E5B76A-CA64-4569-B639-0F50CF4FB537}\icon.ico</DisplayIcon>
      <DisplayVersion>2.0.8.8511</DisplayVersion>
      <EstimatedSize />
      <InstallDate>2017-12-02T00:00:00</InstallDate>
      <InstallLocation>C:\Program Files\AMI\DuOS</InstallLocation>
      <InstallSource>C:\Users\rafae\AppData\Local\Temp\2017122-125128</InstallSource>
      <Is64Bit>X64</Is64Bit>
      <IsProtected>false</IsProtected>
      <IsRegistered>true</IsRegistered>
      <IsOrphaned>false</IsOrphaned>
      <IsUpdate>false</IsUpdate>
      <IsValid>true</IsValid>
      <ModifyPath>MsiExec.exe /X{25E5B76A-CA64-4569-B639-0F50CF4FB537}</ModifyPath>
      <Publisher>American Megatrends Inc.</Publisher>
      <QuietUninstallString>MsiExec.exe /qb /X{25e5b76a-ca64-4569-b639-0f50cf4fb537} REBOOT=ReallySuppress /norestart</QuietUninstallString>
      <RatingId>{25E5B76A-CA64-4569-B639-0F50CF4FB537}</RatingId>
      <RegistryKeyName>{25E5B76A-CA64-4569-B639-0F50CF4FB537}</RegistryKeyName>
      <RegistryPath>HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{25E5B76A-CA64-4569-B639-0F50CF4FB537}</RegistryPath>
      <SystemComponent>false</SystemComponent>
      <UninstallerFullFilename>C:\Windows\Installer\616fc9b.msi</UninstallerFullFilename>
      <UninstallerKind>Msiexec</UninstallerKind>
      <UninstallerLocation>C:\Windows\Installer</UninstallerLocation>
      <UninstallString>MsiExec.exe /X{25E5B76A-CA64-4569-B639-0F50CF4FB537}</UninstallString>
    </ApplicationUninstallerEntry>
  </Items>
</ApplicationEntrySerializer>

**Comment by johnsmith45213** [comment]
After I used the portable version for uninstall Java x86x Java x64, Visual C++ and Net Framework, always what I open and close the portable version I see error: "Windows cannot find" CleanLogs. bat "..."

**Comment by Klocman** [comment]
The error you are getting is not caused by BCU. The application seems to be uninstalled improperly / the uninstaller is corrupted. You can use the "Uninstall Manually" option to force uninstall it.

> After I used the portable version for uninstall Java x86x Java x64, Visual C++ and Net Framework, always what I open and close the portable version I see error: "Windows cannot find" CleanLogs. bat "..."
Update to the newest version of BCU, even if you already have it (something might be corrupted).
