### ISSUE TITLE
Running from UNC path yields "could not find CleanLogs.bat" on application exit

### ISSUE THREAD

**Issue by bionoid** [Klocman/Bulk-Crap-Uninstaller#148]
I have a shortcut on desktop to ``\\NAS\folder\bcuninstaller``, running from this directory works fine, but when exiting a dialog appears "Could not find Cleanlogs.bat. Check your spelling and try again" (translated), with an OK button. 

OS is win10pro, and in case it matters, folder redirection is active for desktop (so users desktop folder is an UNC path as well)

**Comment by Klocman** [comment]
Confirmed, some other things might be buggy as well (anything that uses assembly location and doesn't support UNC paths, e.g. Icon.ExtractAssociatedIcon).
