### ISSUE TITLE
BCUninstaller crashes when selecting Tools -> Clean up Program Files folder

### ISSUE THREAD

**Issue by cornytrace** [Klocman/Bulk-Crap-Uninstaller#151]
On two different windows installation (7 and 10), BCUninstaller crashes when when selecting Tools -> Clean up Program Files folder.
Error message:
System.NullReferenceException
System.Object <SetupListView>b__28_3(System.Object) @ BulkCrapUninstaller.Forms.JunkRemoveWindow+<>c

**Comment by Klocman** [comment]
Confirmed, will fix.
