### ISSUE TITLE
🅵🅾🆁 🅵🆄🅲🅺'🆂 🆂🅰🅺🅴❕ ɪ'ᴍ ᴛᴇʟʟɪɴɢ ʏᴏᴜ, ʟᴏᴜᴅ ᴀɴᴅ ᴄʟᴇᴀʀ:

### ISSUE THREAD

**Issue by Theadd** [Klocman/Bulk-Crap-Uninstaller#159]
# THANK YOU! 

I've just used it once, a few hours ago on a recently installed and clean win10 machine just to get rid of preinstalled games and apps that certainly I'll never run. But this damn **Bulk-Crap-Uninstaller** goes far beyond all other cleaners/*ninjas* that I have ever had the pleasure to try, as back then each one shined in their own uninstalling *unique* style/features plus a lot of other multi-purpose apps features that I'm not looking for when [googling](https://duckduckgo.com/?q=uninstaller+site%3Agithub.com&t=hg&ia=web) for  `uninstaller`-related searches... In short, **TL;DR**: within a few hundred clicks, rebooting and looking around for traces of those things that are not there anymore, I've got a properly **running** (so far) of a **debian netinstall**-equivalent when u choose nothing but the X window system plus some fancy theme, file browser and... well, I've left Edge only for testing followed by some [handy words](http://getfirefox.com), installed drivers included *(crap-free)*. **BCU** just killed 'em all and removed any remaining trace possibily left. No cortana, no windows store apps, not even the windows store itself, and this could be a long list of what's not there anymore.

---

Now, let's do it properly _(kind of)_:
Both <kbd>Send feedback</kbd> buttons return 404
![image](https://user-images.githubusercontent.com/78041/34413742-9b9b603a-ebe5-11e7-9df7-146aba8d155f.png)

---

Good job, keep it up! 👍

**Comment by Klocman** [comment]
# 🅣🅗🅐🅝🅚 🅨🅞🅤
I fixed the redirect, links work fine now. I wonder how long it was broken *shudder*
