### ISSUE TITLE
Leftovers removal assumes apps with similar name are good targets

### ISSUE THREAD

**Issue by DmitriyYukhanov** [Klocman/Bulk-Crap-Uninstaller#161]
Hey, I've installed few 3DMark, 3DMark06, 3DMark Vantage and 3DMark11 apps.
Then I uninstalled 3DMark 11 and leftovers removal assumes it's a good idea to remove items related to the other 3D Mark installations.

Maybe creation date time of files, folders and registry keys could help tune confidence in such cases?

![image](https://user-images.githubusercontent.com/883587/34652503-20297582-f3f0-11e7-9e62-1756bdfb5853.png)

**Comment by Klocman** [comment]
Fixed in ace2c360d1203204e848a1e1138c6e0b6f84ab4b
