### ISSUE TITLE
[Feature request] Faster boot time

### ISSUE THREAD

**Issue by Kristinita** [Klocman/Bulk-Crap-Uninstaller#165]
### 1. Problem

Bulk Crap Uninstaller boot for me very slow — ~8 minutes.

Yes, I have many programs on my PC, but [**another**](https://alternativeto.net/software/bulk-crap-uninstaller/?platform=windows) (non-open source) uninstallers boot much faster.

### 2. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Bulk Crap Uninstaller 4.1.0.31668 (I have this problem in previous versions too),
+ 200+ programs.

### 3. Steps to reproduce

I run `BCUninstaller.exe` file.

### 4. Expected behavior

Boot less than a minute.

### 5. Actual behavior

~8 minutes boot.

![Bulk Crap Uninstaller](https://i.imgur.com/1RyeEbJ.gif)

Thanks.

**Comment by Klocman** [comment]
Hello!

Which steps take the most time? Is BCU getting stuck on a particular step, for example windows features?

**Comment by Kristinita** [comment]
7 minutes out of 8 — `Generating mission information`. BCU not stuck in boot time.

---

I re-run Bulk Crap Uninstaller → BCU program boot for me fast (~20 seconds).

Possibly, BCU boot slow, when I first run BCU after upgrade to new version?

Thanks.

**Comment by Klocman** [comment]
It was probably because BCU had to count how big the applications were on HDD, and there were many small files + a slow/fragmented drive. After first run BCU saved these results so it doesn't have to recalculate it all anymore.

Other applications load quickly because they don't try to detect sizes of applications (and other data) if it's not already in registry.

**Comment by Kristinita** [comment]
@Klocman , when I upgrade BCU to new version, in first run BCU will boot slow?

Thanks.

**Comment by Klocman** [comment]
It depends on the update - if it needs to clear the cache the first load will be slow. These updates will be rare, so don't worry about it.
