### ISSUE TITLE
[Suggestion] Add Automation/Command line option)

### ISSUE THREAD

**Issue by madbomb122** [Klocman/Bulk-Crap-Uninstaller#166]
Not sure if it has been suggestion or if you can do it with your program...

Add an option to send/import a list a programs and it will select anything matching the list given to the program (by GUID and/or Program Name). BCU will then uninstall the programs if given the correct option, otherwise it will just select them to uninstall when program loads.

**Comment by Klocman** [comment]
Hello!

It's actually possible to partially do this. You need to create an advanced filter list, and then start BCU with path to this list as an argument. Unfortunately you can't tell it to uninstall filtered items right away, but all you have to do is click uninstall.

There is a little info about this at the end of the readme.
