### ISSUE TITLE
Bug with Sandboxie

### ISSUE THREAD

**Issue by mikhoul** [Klocman/Bulk-Crap-Uninstaller#178]
Sandboxie is show as if it was using over 13GB ! 😮

Sandboxie 5.20 (64-bit) | Sandboxie Holdings, LLC | 5.20 | 10/01/2012 | 13.21 GB | HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Sandboxie | Nsis | "C:\Windows\Installer\SandboxieInstall64.exe" /remove | "K:\BCUninstaller\UninstallerAutomatizer.exe" Nsis /K "C:\Windows\Installer\SandboxieInstall64.exe" /remove | 

Screenshot: https://i.imgur.com/U3fQl8q.png 

Regards :octocat:

**Comment by Klocman** [comment]
Try Settings > Caching > Clear caches, it should be fixed in the latest version.

**Comment by mikhoul** [comment]
Yep, it fixed the error ! :smile:
