### ISSUE TITLE
Error 1627 when uninstalling some StoreApps e.g. Cortana

### ISSUE THREAD

**Issue by pommedefrance** [Klocman/Bulk-Crap-Uninstaller#181]
Hi !
i love this software but i've got a fail uninstallation with error 1627
someone knows what it means?
Thks !

**Comment by Klocman** [comment]
Hello!

Can you give me more information about what you were trying to uninstall? Or are all uninstallations failing? You can select the application you can't uninstall on the program list, go to File>Export, and send the resulting .xml file here.

**Comment by duttyend** [comment]
Same error when I try to uninstall Cortana for example (on Windows 1709 all latest patches). I killed SearchUI.exe but still the same error unfortunately :-(

**Comment by Klocman** [comment]
This is a known issue, will have a look at it.

**Comment by Klocman** [comment]
Microsoft made some store apps very difficult to remove starting with creators update. This is the result.

Trying to circumvent this is hard and probably not worth the potential damage people might do for little to no benefit.

I made a change that marks these problematic apps as protected + system components, so they won't show up by default, and it will be harder to attempt to uninstall them.

**Comment by GitAlexToTheGreek** [comment]
Hi,

1) Excellent app, thanks for your efforts.
2) Sorry for digging up an old & closed thread. 

3) Requesting feedback on removing the remnants of an Xbox uninstallation... 

Ran as admin with explorer.exe terminated, and BCU successfully cleared the majority of all found references to Xbox except:

<img width="962" alt="1" src="https://user-images.githubusercontent.com/59787873/85264041-f1fe0400-b424-11ea-93e7-16b7a87200a0.png">

<img width="323" alt="2" src="https://user-images.githubusercontent.com/59787873/85264086-03471080-b425-11ea-9605-bfa19e1ac895.png">

Afterwards, searching "Process Explorer", this is what's left:

<img width="488" alt="3" src="https://user-images.githubusercontent.com/59787873/85265120-9fbde280-b426-11ea-8cb6-b5ae55c4734c.png">

Could I just try deleting those two files in safe mode?
Or would any further tweaks to BCU work?

**Comment by CodingMadness** [comment]
Sry to revive thsi thread again, is there really no way of deleting these appes/files? Did they do it impossible to get rid of those?

**Comment by Klocman** [comment]
> Sry to revive thsi thread again, is there really no way of deleting these appes/files? Did they do it impossible to get rid of those?

It's increasingly more difficult with every new version of Windows. I'm very much not up to speed and don't know what it takes to remove those "core" apps now, especially under Win11. I suggest looking online on windows modding forums.
