### ISSUE TITLE
Chocolatey support

### ISSUE THREAD

**Issue by myfairsyer** [Klocman/Bulk-Crap-Uninstaller#184]
Do you support removing chocolatey packages (together with their actual software)?
If not, treat this as a feature request for it! :)

Reference: https://chocolatey.org/docs/commandsuninstall

**Comment by ManlyMarco** [comment]
So it's like BCU but for installing programs. looks good so far! At the moment there is no support, but I will definitely add it. Thank you for the suggestion!

**Comment by Klocman** [comment]
So it's like BCU but for installing programs. looks good so far! At the moment there is no support, but I will definitely add it. Thank you for the suggestion!

**Comment by Klocman** [comment]
I believe the deed is done. BCU will now detect all local Chocolatey packages and add them to list. If possible they will be merged with already detected applications. These are always uninstalled from Chocolatey, either as the main means of uninstalling, or during junk scan (with -n --skipautouninstaller).

**Comment by gep13** [comment]
Why skipping the auto uninstaller?

**Comment by gep13** [comment]
Great work by the way!

**Comment by Klocman** [comment]
By the time it gets to junk scan the application is supposed to be more or less completely uninstalled. I want to avoid errors caused by missing uninstallers, so I just remove the package.

If BCU decides to uninstall the application through Chocolatey it doesn't use these flags.

**Comment by myfairsyer** [comment]
I don't really know Chocolatey well, but **as far as I understood/concludedit**

- a) you're supposed to be able to just [`cuninst tool`](https://chocolatey.org/docs/commandsuninstall) to uninstall tools without worrying
- b) to uninstall the tool itself chocolatey just uses the tool's own "cli uninstaller" (I think most packages are with MSI (un)installers) alongside chocolatey's own management (removing the package from the list, removing the shim &c.) but doesn't actively search for leftovers or keep track of what the tool's (un)install routines actually do

**Comment by Klocman** [comment]
Thank you for the info, it sounds like I made the correct decision to treat Chocolatey as a loud uninstaller then.

**Comment by gep13** [comment]
>  @Klocman said..
Chocolatey as a loud uninstaller then

Can you elaborate simply on the meaning of this?

**Comment by Klocman** [comment]
Basically assume that user input will be needed, so look for a better ("quiet") alternative.

**Comment by gep13** [comment]
>@Klocman said...
Basically assume that user input will be needed

So, that will certainly be true of some packages, but a reasonably high percentage of packages will be correctly uninstalled through the auto-uninstaller.
