### ISSUE TITLE
FR: npm/yarn/node_modules

### ISSUE THREAD

**Issue by myfairsyer** [Klocman/Bulk-Crap-Uninstaller#185]
Feature Request: Support `node_modules`, as installed by `npm`, `yarn`, `pnpm`, `cnpm`, `npminstall` etc.

They do not only contain small programming libraries, but also development tools, like `cypress` (~200 MiB).

I guess it makes sense to filter local installs and only show global ones by default but to enable to display the local ones aswell.

**Comment by Klocman** [comment]
Reviewed it, and I don't think the benefit-to-work ratio is too small. I will gladly merge if someone else writes this feature, but I'm not going to work on it personally.
