### ISSUE TITLE
BCU tries to uninstall already removed apps

### ISSUE THREAD

**Issue by megapro17** [Klocman/Bulk-Crap-Uninstaller#187]
Select any app, uninstall it
Next time select other app, uninstall it. BCU will delete the selected application, and application that has already been deleted, and it can't been unchecked.

**Comment by megapro17** [comment]
![1](https://user-images.githubusercontent.com/16743370/40575567-ec05b62c-60ef-11e8-8f72-38b903dc42ae.PNG)
![2](https://user-images.githubusercontent.com/16743370/40575570-f9d88a40-60ef-11e8-9162-cefc82fa6ca5.PNG)

**Comment by Klocman** [comment]
Thanks for the report, I'll look into it.
