### ISSUE TITLE
[Suggestion] Could use translation platform

### ISSUE THREAD

**Issue by MS-PC2** [Klocman/Bulk-Crap-Uninstaller#210]
Crowdin:   https://crowdin.com
Weblate:   https://weblate.org
Transifex:  https://www.transifex.com

Suggestion for faster translations. All these platforms can be synchronized with GitHub.

**Comment by Klocman** [comment]
Good suggestion, I was thinking about doing something to make translating less messy.

These platforms don't look like they will work for this purpose. Ideally people would just create a fork for their translation and start a PR when ready, but it's probably not going to happen.

I'll think about this some more before doing anything. If anyone has any ideas please share.

**Comment by Klocman** [comment]
For the moment I decided to release an updated localization pack together with each version release. It's easy to grab it and check in [ResxTranslator](https://github.com/HakanL/resxtranslator) if any missing translations appear.
