### ISSUE TITLE
Review BCU performance (read NTFS' MFT?)

### ISSUE THREAD

**Issue by myfairsyer** [Klocman/Bulk-Crap-Uninstaller#215]
BCU's startup and scan time can be quite long.
Do you know where current performance bottlenecks are?
Searching the registry? Finding files? Reading files?

If it's the second might it help (and be worth the effort) to scan the [`MFT`](https://docs.microsoft.com/en-us/windows/desktop/fileio/master-file-table)?

**Comment by myfairsyer** [comment]
Related: #168 #165

**Comment by Klocman** [comment]
I'm testing an implementation of using MFT on a new branch https://github.com/Klocman/Bulk-Crap-Uninstaller/tree/ntfs-mft

For now the implementation is inefficient and needs work so I don't recommend using it.

**Comment by Kiina** [comment]
I noticed the startup to be really long. Like 20+ minutes on a fairly modern system long. Does it scale with disk space? Also searching for steam games takes kinda long time with 2400 games installed. Maybe a way to skip it, as I can uninstall them perfectly from within steam in bulk.

**Comment by Klocman** [comment]
The scan time scales with amount of folders and files in application folders (e.g. program files) and disk speed.

You can disable scanning Steam games from the settings.

**Comment by Klocman** [comment]
So far it looks like reading MFT is not going to be much faster, if at all. It takes quite a long while to read and parse it, which offsets the gains. It's also not as safe, since reading MFT ignores file security settings and attributes, which would most likely bring in new bugs.

For the moment this idea is shelved, unless someone else wants to give it a try.

**Comment by myfairsyer** [comment]
I don't know how widespread `Everything Search` (ES) is.
If it "turns out"* to be used by a significant number of users, might you consider BCU trying to use it as a scanning backend and only falling back to its native behavior when it isn't available?
- MFT parsing gets way easier like that:
  - You wouldn't have to implement and maintain the MFT parsing, but a well known tool, that's being maintained for 15 years already.
  - The MFT wouldn't have to be parsed by BCU so you would not need admin rights to access it
  - The MFT wouldn't have to be parsed on runtime. ES takes care of creating an index and keeping it up to date.
- You still would not respect the file security settings. Do you have specific scenarios in mind where they matter for scanning the disk and recognizing the installed software?

* I'm not talking about actually counting/"spying"/doing telemetry here, but rather some intelligent guess based on the overall popularity of the tool

**Comment by myfairsyer** [comment]
There are several means of communicating with `ES`.

The most relevant one for this suggestion probably being [IPC](https://www.voidtools.com/support/everything/sdk/ipc/) which seems to be way more feasible when using the [SDK](https://www.voidtools.com/support/everything/sdk/) ([C# example](https://www.voidtools.com/support/everything/sdk/csharp/)) provided and as an unglier fallback/alternative maybe using the [CLI client](https://www.voidtools.com/support/everything/command_line_interface/).

Other interfaces include the [HTTP Server](https://www.voidtools.com/support/everything/http/) (which isn't installed by default and renders the results in HTML, which you surely wouldn't want to parse) and [ETP](https://www.voidtools.com/support/everything/etp/), which is more relevant when communicating over the network. ES's [Windows Service](https://www.voidtools.com/support/everything/everything_service/)'s documentation says it doesn't have an interface (but you have the IPC interface and the SDK around it after all)

Condensed (and hopefully not messed up) version of their C# example code:

```csharp
public class ESearch {
    const int EVERYTHING_REQUEST_FILE_NAME = 0x00000001;
    
    [DllImport("Everything64.dll", CharSet = CharSet.Unicode)]
    public static extern UInt32 Everything_SetSearchW(string lpSearchString);
    
    [DllImport("Everything64.dll")]
    public static extern bool Everything_QueryW(bool bWait);
    
    [DllImport("Everything64.dll", CharSet = CharSet.Unicode)]
    public static extern IntPtr Everything_GetResultFileName(UInt32 nIndex);
    
    [DllImport("Everything64.dll")]
    public static extern void Everything_SetRequestFlags(UInt32 dwRequestFlags);
    
    private string getFirstFileName(string querystring) {
        Everything_SetSearchW(querystring);
        Everything_SetRequestFlags(EVERYTHING_REQUEST_FILE_NAME);
        Everything_QueryW(true);
        return Marshal.PtrToStringUni(Everything_GetResultFileName(0));
    }
}
```

**Comment by Klocman** [comment]
Everything is currently used through the command line tool to get directory sizes (if it's installed) https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/f9ddbea5a3cd881a7233e61f50eb98d19596b3bd/source/UninstallTools/Factory/InfoAdders/FastSizeGenerator.cs#L81-L94

I didn't add more functionality because the size scan was the main bottleneck and implementing a full wrapper around file IO would need a lot of work for potentially little return.

**Comment by myfairsyer** [comment]
Nice, I didn't know you already do use ES!
