### ISSUE TITLE
[Suggestion] Support to unistall Pro Tools First

### ISSUE THREAD

**Issue by Tox86** [Klocman/Bulk-Crap-Uninstaller#218]
Hello, it's possible add the ability to uninstall Pro Tools First.
![pro tools first support](https://user-images.githubusercontent.com/7013508/45858287-11896980-bd33-11e8-89fb-4563fee1573e.png)
Cheers.

**Comment by Klocman** [comment]
Hello! Please try to run Quick filters > Show Everything and check if Pro Tools appears on the list.

**Comment by Tox86** [comment]
Now works, Thanks.
[**CLOSED**]
