### ISSUE TITLE
BCU errors on moved apps to non-system drive (new path)

### ISSUE THREAD

**Issue by Jimbazuka** [Klocman/Bulk-Crap-Uninstaller#219]
In windows 10, Microsoft Store Apps can be moved to a new drive (see https://www.windowscentral.com/how-install-apps-separate-drive-windows-10)

If you do that and then attempt to uninstall via BCU, you get an error message (see attached)
![2018-09-24 09_20_43-glasspanelform](https://user-images.githubusercontent.com/7934633/45966285-370bc100-c01a-11e8-8729-ec91b43b6b0e.jpg)
![2018-09-24 09_22_26-glasspanelform](https://user-images.githubusercontent.com/7934633/45966286-370bc100-c01a-11e8-967c-dba822371896.jpg)

**Comment by Klocman** [comment]
Hello!

I can't seem to be able to reproduce this issue. I can uninstall Netflix without errors. At exactly what point does the error happen? Is it during the junk scan?
