### ISSUE TITLE
BCU asks to delete Choco.exe when uninstalling Google Chrome

### ISSUE THREAD

**Issue by ILPlais** [Klocman/Bulk-Crap-Uninstaller#221]
If Google Chrome has been installed using Chocolatey. Bulk-Crap-Uninstaller proposes to delete the program `choco.exe` when deleting the remains.

![2018-10-23 11_28_53-suppression des vestiges](https://user-images.githubusercontent.com/2880695/47351726-e50d9800-d6b8-11e8-9c8d-e090ab340722.png)

**Comment by Klocman** [comment]
Thank you for the report, this turned out to be a relatively major issue in a different part of the code. Fix will be included in upcoming release.
