### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by 1337haXXor** [Klocman/Bulk-Crap-Uninstaller#223]
Trying to use the portable version, first time. Runs through analyzing everything, but on or just before "Searching for start-up entries" I get a System.ArgumentException error. It says:
"Invalid Unicode code point found at index 37.
Parameter name: strInput."

Target Site: "System.String Normalize(System.String, System.Text.NormalizationForm) @ System.Text.Normalization"

EDIT: Same issue with earlier versions, 4.10 and 4.04, and with the .exe installer, installing portable or standard.

**Comment by Klocman** [comment]
I believe this has been fixed a few days ago, can you try the Debug.zip from here? https://github.com/Klocman/Bulk-Crap-Uninstaller/issues/222#issuecomment-435599409

**Comment by 1337haXXor** [comment]
Hmm, this one crashes it instantly.

Exception: System.Reflection.ReflectionTypeLoadException

Target Site: System.RuntimeType[] GetTypes(System.Reflection.RuntimeModule)

Most of the exception details seem the same.

**Comment by Klocman** [comment]
Did you download the Debug.zip from linked post and extract it to a new folder? It shouldn't crash like this unless some files get mixed in with other version of BCU.

**Comment by 1337haXXor** [comment]
Yup, Debug had 3 files: the .exe, and 2 DLLs. I took the portable of 4.11 and copied those 3 files in, replacing the old ones.

Some system info, Windows 10, 1803. I've made a large amount of significant modifications to the system: disabling as much telemetry as possible, disabling antivirus, Cortana, caching, and more. Not sure if those would have an effect.

**Comment by Klocman** [comment]
That's the wrong zip, you need this one https://github.com/Klocman/Bulk-Crap-Uninstaller/files/2545110/Debug.zip

**Comment by 1337haXXor** [comment]
Aha, the link took me to an earlier comment.

Yes, that one works! I did see the earlier bug, but it seemed that my error was different from the other user's. Sorry! Should I continue using this debug version until whenever the next update is?

Thanks so much!

**Comment by Klocman** [comment]
You can use the debug build, just keep in mind that it has "Simulate uninstalation" enabled by default.
I will release an update in a couple of days so you can wait for that also.
