### ISSUE TITLE
Wild Tangent Games

### ISSUE THREAD

**Issue by paul1149** [Klocman/Bulk-Crap-Uninstaller#224]
I have no idea what is happening under the hood, but each time I've tried BCU uninstalling Wild Tangent Games messes it up. The BCU monitor window just keeps cycling interminably. I try hitting Skip, or Terminate, and nothing seems to happen. Ditto, closing the BCU monitor window. Then I hit Cancel, and the entire BCU interface closes, to be replace by its Clean-up window. I execute that, thinking the program is over, but no, now a whole bunch of programs begin uninstalling automatically.

I have NO idea what is going on, or what the logic behind this is. Most probably this is my deficiency, but I just don't get it. I guess next time I'll try without checking WT.

**Comment by Klocman** [comment]
First of all, update to the latest version and test again. A lot of fixes were made since 4.5
If it still doesn't work then in main menu of BCU select the applications that cause issues, click File > Export, and send me the .xml file.

**Comment by paul1149** [comment]
I guess then that the version numbering system has been changed? I will do as you say on the next machine. Thanks.
