### ISSUE TITLE
Version issue ? 4.12.2-4.12.3

### ISSUE THREAD

**Issue by GrosBourrin** [Klocman/Bulk-Crap-Uninstaller#227]
i have update to 4.12.2 then it says at start that there is a 4.12.3 with same changelog  that doesn't exists ! 
x64 version - windows 10 1809 x64... i must say that your soft is a must have !
![2019-01-13_04h33_23](https://user-images.githubusercontent.com/40931468/51081297-a81bd500-16ec-11e9-9de4-9aa8a886d26d.png)

**Comment by Klocman** [comment]
Fixed it, just a typo. It shouldn't appear anymore.
Thanks!
