### ISSUE TITLE
Prefetch Files

### ISSUE THREAD

**Issue by KayzzenD** [Klocman/Bulk-Crap-Uninstaller#229]
By comparing the override removal between BCUninstaller and Revo Uninstaller, Revo Uninstaller removes Prefetch Files. I think it can improve file removal.

Example:
Microsoft Visual C ++ 2015 Redistributable (x86)
C: \ Windows \ Prefetch \ VCREDIST_X86.EXE-6ACF1352.pf

I do not know if there is a need to remove these files, but it will tip.

Sorry if I said bullshit =)

**Comment by Klocman** [comment]
It was already considered in #212, but I didn't see the need to add this at the time. The impact of these files is minimal and old prefetch files can get removed in many different ways. I will leave this issue up on low priority for completion, eventually it might get implemented :)
