### ISSUE TITLE
[Question] How restore removed file?

### ISSUE THREAD

**Issue by Kristinita** [Klocman/Bulk-Crap-Uninstaller#23]
## 1. Briefly

I removed my files use Bulk Crap Uninstaller. I don't know, how I can restore my files, if it is possible.

---

---

## 2. Detail

I quiet delete use BCU my program [**The Wonderful Icon**](http://www.thewonderfulicon.com/). In delete process I see window, that recommend close windows with Firefox and Miranda NG programs like in image:

![Firefox Miranda NG](http://i.imgur.com/O0O1C3I.png)

But I not close Firefox and Miranda NG and continued deletion. After delete The Wonderful Icon, I see that delete

+ Firefox bookmarks, history, cookies, settings of addons, log on data;
+ Miranda NG correspondence and settings.

Were removed `.sqlite` files. I can not restore it.

---

---

### 1. Recycle bin

I don't find my `.sqlite` files in my recycle bin.

### 2. System restore

System restore is enabled in my settings.

![System restore](http://i.imgur.com/uuQDq0K.png)

I restore my Windows 10, but neediest files not restore.

### 3. Third-party soft

I try restore my files use [**Recuva**](https://alternativeto.net/software/recuva/) and [**PhotoRec**](https://alternativeto.net/software/photorec/) programs, but I have not success.

---

---

## 4. Request

If restore files not possible at the moment, I offer option `Delete to recycle bin`, that files, delete via Bulk Crap Uninstaller delete to recycle bin, not forever.

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Bulk Crap Uninstaller:**
3.5.0.36158

Thanks.

**Comment by Klocman** [comment]
## Deleted files
BCU always tries to delete files to the recycle bin. The files might have been lost if the recycle bin is disabled or too small on that drive. 

Unless you enabled system restore on the drive with files, and enabled protection of data, it won't backup your files.

If restore programs don't see your files, maybe they were not deleted?

## The Wonderful Icon closing all the programs
It's possible that this application adds hooks to running processes. BCU detects that, and asks to close everything with the hook loaded to be able to remove the hook. Or it might be a bug.

Did BCU ask to delete Firefox and Miranda files? That shouldn't happen and is definitely a bug.

**Comment by Kristinita** [comment]
@Klocman,

### 1. Answers

> BCU always tries to delete files to the recycle bin.

I don't find in my recycle bin files of Miranda NG, Firefox or The Wonderful Icon.

> if the recycle bin is disabled

No, it's enabled for me.

> or too small on that drive.

I have 370 GB free disk storage in hard drive with my recycle bin.

> Unless you enabled system restore on the drive with files

System restore enabled for me.

> enabled protection of data

I'm sorry, what is «protection of data» in this context?

> If restore programs don't see your files, maybe they were not deleted?

I use [**Agent Ransack**](https://www.mythicsoft.com/agentransack) for file searching on my computer. I search in my computer [**some files, where Firefox saved my data**](http://kb.mozillazine.org/Profile_folder_-_Firefox), but I have not success.

---

### 2. Steps to reproduce

I again install The Wonderful Icon for me → I open BCU → select TWI → `Uninstall quietly` → I to see this window:

![TWI](http://i.imgur.com/xj4OB6W.png)

In pastime, I see similar window with Firefox and Miranda NG items. I could be wrong, but likely I click to `Ignore` → I get unexpected behavior.

---

### 3. File deletion

For example, now I quietly uninstall use BCU [**PomoTime**](https://chocolatey.org/packages/PomoTime) application. Before uninstalling PomoTime have 52,6 MB size:

![Before](http://i.imgur.com/KrcmtwS.png)

I restore PomoTime into my recycle bin and the program have only 496 bites:

![After](http://i.imgur.com/ssC751W.png)

Where now I can find other files program? And program is not only `С:\Program Files\PomoTime`, program, for example, have data in `%APPDATA%`, but I can not see these data in my recycle bin.


Thanks.

**Comment by Klocman** [comment]
#### # 1
> I'm sorry, what is «protection of data» in this context?

Sorry, my mistake. System restore can't restore user files. You might be able to go to folder/file properties > Previous Versions and restore some files from there. It might not work if you set too low disk space usage for system restore.

#### # 2
I will install TWI and look into this. Thank you for the report.

#### # 3
> I don't find in my recycle bin files of Miranda NG, Firefox or The Wonderful Icon.

> For example, now I quietly uninstall use BCU PomoTime application [...]

Just to be clear, BCU does not backup the applications before uninstalling them. It only backups things that are left after the uninstallation in case they are still needed.
PromoTime was 52,6 MB before uninstallation. Its uninstaller was executed, and it left 496 bytes of leftovers. These leftovers are what BCU deletes to the recycle bin.

**Comment by Klocman** [comment]
TWI uninstall wanting to close all these applications is normal, it puts hooks into processes that need to be closed.

**Comment by Kristinita** [comment]
@Klocman , it is really bad behavior — remove without possibilities of restore data of programs, which I don't want to remove.

Please, at least make a popup with capital letters, if user press or click to `Ignore` in uninstalling process, for example:

> WARNING!!! You risk lose and not restore data of non-killed programs! Highly recommended kill all process!!!

If I would see this popup in the day of removal, I would have killed Miranda NG and Firefox processes and would save my data.

Thanks.

**Comment by Klocman** [comment]
In this case killing the processes would not save your data, because the application's own uninstaller deleted it. There's nothing I can do about that. 
If you want BCU to back-up everything, then you have to use the "Uninstall Manually" option.
I will look into adding some warnings about this.
