### ISSUE TITLE
Duplicated Entries?

### ISSUE THREAD

**Issue by otavio-silva** [Klocman/Bulk-Crap-Uninstaller#230]
It usually happens with Steam games but the same software has two entries. Some examples:

- Nioh: Complete Edition
![92c2f165-f06b-494e-8675-52cfb3c7efba](https://user-images.githubusercontent.com/22914610/51869737-9bc48880-2338-11e9-97fe-9d28729f5502.png)
- Sunset Overdrive
![ec43864c-1258-474e-a649-89345ba85577 bmp](https://user-images.githubusercontent.com/22914610/51869817-dd553380-2338-11e9-987c-ab7e120bcb6f.png)
- Hellblade: Senua's Sacrifice
![db97ea9c-e3ef-483f-828e-9760782732b2 bmp](https://user-images.githubusercontent.com/22914610/51870085-b8ad8b80-2339-11e9-8d7c-6bf50f415484.png)
- MSI Battery Calibration (a case of something that is not a Steam game)
![47a54485-afb7-4231-af02-dcf518756c36 bmp](https://user-images.githubusercontent.com/22914610/51870118-cd8a1f00-2339-11e9-88e9-a9d67974f948.png)

While writing this, I noticed something. Both Nioh and Hellblade installation paths do not exist (I recently moved my Steam games to another folder) and in Sunset Overdrive only one of them exists. But in the battery calibration software it's the same path but different uninstallation commands. Maybe I'm missing something or just being dumb, but I would like some help understanding this, thanks in advance. Also, 
some info:

- OS: Windows 10 Education 1809
- Version: BCUninstaller 4.12.2.23324 64bit (installed through Chocolatey)

**Comment by Klocman** [comment]
Weird, the Steam entries should get merged. Can you select the duplicate entries and send me result of File > Export?

The battery calibration is correctly split into two - it has two uninstallers registered (one of them is usually hidden).

**Comment by Klocman** [comment]
Can you also send SteamHelper.log and BCUninstaller.log?

**Comment by otavio-silva** [comment]
Here:
[SteamHelper.log](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/2808702/SteamHelper.log)
[BCUninstaller.log](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/2808703/BCUninstaller.log)

**Comment by Klocman** [comment]
Added a fix that could potentially fix it, it'll be available shortly in the upcoming release.

**Comment by otavio-silva** [comment]
Thanks for the help!
