### ISSUE TITLE
Better (Windows 10) system theme support by utilizing XAML Islands

### ISSUE THREAD

**Issue by jebeld17** [Klocman/Bulk-Crap-Uninstaller#233]
Bulk Crap Uninstaller (BCU) can support system themes a lot better by utilizing XAML Islands.
By utilizing XAML Islands for theme support in BCU and other Win32 or .NET apps, BCU (or these apps) can tap into the same design libraries as UWP/Store apps, therefore offering users a more consistent user interface (UI).

Sources:
[A Deep Dive into XAML Islands, Part One](https://blogs.windows.com/buildingapps/2018/11/02/xaml-islands-a-deep-dive-part-1/)
[A Deep Dive into XAML Islands, Part Two](https://blogs.windows.com/buildingapps/2018/11/08/xaml-islands-a-deep-dive-part-2/)

**Comment by Klocman** [comment]
This looks interesting, thanks for letting me know!

So far I've held back on introducing any dependencies on new Windows versions in order to have BCU work on as many systems as possible. Since W10 market share is gaining I will look into moving to UWP model sometime soon. 

Related to #226, possibly #228

**Comment by jebeld17** [comment]
@klocman the great thing about XAML Islands is that your app doesn't need to be a UWP in order to take advantage of these theming resources. 

XAML Islands allows any Windows app to take advantage of UWP theming resources.

**Comment by Klocman** [comment]
Looks like moving to UWP will be straight up not possible, at least without hacky workarounds. UWP have much, much less permissions and can't run as administrator so BCU would simply not work. This means XAML Islands is most likely the way to go.

I took a brief look at how to use them but didn't find much info on how to use them, I'll have to look into it some more when I have the time.

**Comment by jebeld17** [comment]
Microsoft Store is actually allowing apps with Admin permissions into the Store, now.

It's all on a case-by-case basis to get approved.

**Comment by Klocman** [comment]
Forms in .NET 5 seem to support DPI scaling well, so I'll be going with that instead of rewriting the UI in XAML.
