### ISSUE TITLE
The loading bar on top issue. 

### ISSUE THREAD

**Issue by jin8864** [Klocman/Bulk-Crap-Uninstaller#238]
Thanks for the great app. I love this app and use constantly. 
One thing I found that is annoying about this app is that the loading bar is displayed on top every time it is launched. 
Sometimes it blocks the center of the screen and I couldn't see the important part of my web page. I cannot even move it. 
Hope it will be fixed in the next version. 

![BulkCrap Uninstaller issue](https://user-images.githubusercontent.com/17965348/63145723-70cf2700-c033-11e9-91d3-8e2129046514.JPG)

**Comment by Klocman** [comment]
Fixed in the upcoming release, thank you for the report!
