### ISSUE TITLE
Can't detect apps from scoop

### ISSUE THREAD

**Issue by SonOfDiablo** [Klocman/Bulk-Crap-Uninstaller#239]
Greetings,

It seems that BCU isn't able to detect apps installed with Scoop if the user has changed the SCOOP Environmental Variable.

As mentioned in the following issue over at the Scoop Repo: https://github.com/lukesampson/scoop/issues/249

A user can change the SCOOP Environmental Variable to get Scoop to install itself and other apps in a custom directory.

Would it be possible to get BCU to either use the SCOOP Environmental Variable or let the user set their own Scoop directory?

**Comment by Klocman** [comment]
Hello!

Thanks for the report, I'll get it fixed before the upcoming release. Can you help me understand how the custom paths work?
- If the custom path is specified, are scoop.ps1 and other scoop files located in the custom path, or are they still in the default path inside user profile?
- Can both the default directory and the user-specified directory be used at the same time, or if the custom directory is specified all apps have to be inside of it?

**Comment by SonOfDiablo** [comment]
As far as I can tell, specifying a custom path will cause Scoop to install everything in that path instead of the default install directory.
And it doesn't seem as if you can use both the default and a custom directory at the same time no.

So in short, if the Environmental Variable is specified before installing Scoop, Scoop will only use the set path and not the default path at all.

**Comment by Klocman** [comment]
Can you test if this build detects everything correctly?
[Release.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/3643283/Release.zip)

**Comment by SonOfDiablo** [comment]
It works perfectly.

**Comment by Klocman** [comment]
Thank you!
