### ISSUE TITLE
Create Restore Point Greyed out, yet I can manually create restore points

### ISSUE THREAD

**Issue by perrybucsdad** [Klocman/Bulk-Crap-Uninstaller#240]
I'm unable to create a restore point in your app as the function is greyed out, but I AM able to create restore points manually.  Why is this happening and is there something I can do to fix it? I have attached a screenshot of my registry entry for [HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SystemRestore]

![2019-09-23_10-32-25](https://user-images.githubusercontent.com/24876912/65435364-68b29600-ddee-11e9-9437-857c2e9e2f84.png)

**Comment by Klocman** [comment]
Thanks, fixed in the upcoming release.

**Comment by perrybucsdad** [comment]
Thanks!  When will the new release come out?

**Comment by Klocman** [comment]
Right now.
