### ISSUE TITLE
可以添加中文简体吗

### ISSUE THREAD

**Issue by OR120** [Klocman/Bulk-Crap-Uninstaller#241]

**Comment by Klocman** [comment]
Hello,

Yes, of course, it would be great to have a Chinese translation!

To get started, download the latest localization pack from releases ([this](https://github.com/Klocman/Bulk-Crap-Uninstaller/releases/tag/v4.13) release has the latest localization pack currently). Extract the pack somewhere safe and see the Readme file for further instructions.

If you have any issues or questions, please feel free to ask here.

**Comment by Klocman** [comment]
Closing because of no replies.
