### ISSUE TITLE
Export information list to csv/excel?

### ISSUE THREAD

**Issue by andrizmitnick** [Klocman/Bulk-Crap-Uninstaller#243]

**Comment by Klocman** [comment]
Do you mean the same export as the .xml from `File > Export` but in a different file format? You should be able to import the .xml into most spreadsheet applications, is there an issue with doing this?

**Comment by andrizmitnick** [comment]
ah sorry, i've never found that option. thanks for pointing that out.

**Comment by Klocman** [comment]
No problem, happy to help.

**Comment by Bluscream** [comment]
@Klocman any idea why those are greyed out? Didn't find anything in the manual at all about exporting

![](https://i.imgur.com/g1W5vFv.png)
