### ISSUE TITLE
Show ROT13 paths in readable form

### ISSUE THREAD

**Issue by JanPokorny** [Klocman/Bulk-Crap-Uninstaller#245]
When uninstalling Python 3.7.3 installed through Scoop, some paths show up as ROT13. (Related to #29, dee9452) In order to review them before deletion, it would be great if they were displayed in the non-ROT13 form. (But just nice-to-have, I don't suppose those registry entries are very important.)

![obrazek](https://user-images.githubusercontent.com/4580066/68552695-0e12df00-041a-11ea-9f8c-1825ac42a8c7.png)

**Comment by Klocman** [comment]
These entries are just a recently opened file list, they can be safely removed. BCU actually does decode ROT13 internally but doesn't show the result. I'll see if it's easy to fix.
