### ISSUE TITLE
Can't go on after deleting leftover files. 

### ISSUE THREAD

**Issue by jin8864** [Klocman/Bulk-Crap-Uninstaller#246]
![BCuninstaller](https://user-images.githubusercontent.com/17965348/69801745-489eb900-121b-11ea-836a-5a508739552b.JPG)

As you can see in the screenshot, I can't go on after deleting tons of leftover files because the pop-up menu doesn't show fully on the display. I can't even close the app. Hope it will be fixed in the next update. 
Thanks!

**Comment by Klocman** [comment]
Can you send your bcuninstaller.log file? It should have the whole error in it. If this happens again you should be able to skip the backup by pressing left and then enter.
