### ISSUE TITLE
Ugly font

### ISSUE THREAD

**Issue by Why7090** [Klocman/Bulk-Crap-Uninstaller#249]
While the title and menu bars are normal, all text inside the window aren't anti-aliased and makes reading very difficult.

My system font is Microsoft YaHei.

![image](https://user-images.githubusercontent.com/16470555/72688173-a9879680-3ad2-11ea-8a00-b418618e74de.png)

**Comment by Klocman** [comment]
Try forcing BCU language to English in settings, this font is fairly common when running winforms apps on a system set to some of the Asian locale settings.

**Comment by Why7090** [comment]
> Try forcing BCU language to English in settings, this font is fairly common when running winforms apps on a system set to some of the Asian locale settings.

Thank you. I fixed it by setting font links.
