### ISSUE TITLE
French translation improvements

### ISSUE THREAD

**Issue by Klocman** [Klocman/Bulk-Crap-Uninstaller#25]
> In French, we can say [Remplissage de la liste de désinstalleurs], but this is not correct.
> I propose [Lecture des programmes installés] that matches this initialization phase.
> Or, but longer [Création de la liste des programmes installés].
> When you say a [liste de désinstalleurs=(uninstaller)], this is not correct. The list which you show is programs and your software is a uninstaller. You see the difference...

**Comment by Ignamarte** [comment]
I just submitted a PR to fix the translation

**Comment by Klocman** [comment]
I just merged it in, thank you!
