### ISSUE TITLE
Entry automatic starts

### ISSUE THREAD

**Issue by nico92GitHub** [Klocman/Bulk-Crap-Uninstaller#250]
Hello!
We've already had contact at the beginning of BCU (I had proposed to display the total size of the displayed items).

Well, in [Quick Filters] I selected Automatic starts only.
In the list that is displayed, I see the entry "Microsoft Flight Simulator X Demo".
However, Flight Simulator does't starts automatically.

With the System Explorer software, I can see the entries classified in autostart and Flight Simulator is not there. See attached screenshots, please.
BCU has a setup with many features that are a bit beyond me, I must say ;(

So I may have checked or unchecked something somewhere that generates the display of this Flight Simulator element?

When you have a moment to respond, since there is no particular problem,
Regards,
Nicolas

![BCU](https://user-images.githubusercontent.com/22394276/73173866-a742bf00-4106-11ea-8c45-9e3a498cc683.jpg)
![SE](https://user-images.githubusercontent.com/22394276/73173871-aa3daf80-4106-11ea-98b5-76233b3d1423.jpg)

**Comment by nico92GitHub** [comment]
![BCU_02](https://user-images.githubusercontent.com/22394276/73174066-233d0700-4107-11ea-8c15-76fc0ec59a2b.jpg)
Oops! Forgot that screen view.

**Comment by Klocman** [comment]
Open BCU's startup manager and check in that, the system explorer
screenshot might not be showing everything.

If you don't see anything obvious then select the flight simulator and send
the result of file > export, then select everything in startup manager and
send an export of that.

**Comment by nico92GitHub** [comment]
Thank you for your return.


In fact, there is no flight simulator in startup manager window. So you will find in attachment the Flight Simulator export.

I should point out that Flight Sim is installed in (even if this info is in the export):
"E:\Program Files (x86)\Microsoft Games\Microsoft Flight Simulator X Demo\fsx.exe"




By the way, I see that BCU is even more powerful than I thought! With all the display options in this startup manager window, Houlala ! Very strong Marcin :-)

This will allow me to delete items that no longer exist as Freefirewall and maybe other entries.


Pending your return,
best regards,
Nico



Open BCU's startup manager and check in that, the system explorer

screenshot might not be showing everything.



If you don't see anything obvious then select the flight simulator and send

the result of file > export, then select everything in startup manager and

send an export of that.



On Mon, Jan 27, 2020 at 1:16 PM nico92GitHub <notifications@github.com>

wrote:

**Comment by Klocman** [comment]
Looks like your attached files were not sent properly. Try commenting on
github and dragging the files into the text field.

**Comment by nico92GitHub** [comment]
I hope it's okay...

Microsoft Flight Simulator X Demo | Microsoft Game Studios | 10.0.60905 | 27/11/2019 | 1.22 Go | HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\InstallShield_{B98A34C0-A6A2-4087-B272-557C1C6D0A07} | Unknown | C:\PROGRA~2\COMMON~1\INSTAL~1\Driver\11\INTEL3~1\IDriver.exe /M{B98A34C0-A6A2-4087-B272-557C1C6D0A07}  |  | 

Microsoft Flight Simulator X Demo - C:\PROGRA~2\COMMON~1\INSTAL~1\Driver\11\INTEL3~1\IDriver.exe /M{B98A34C0-A6A2-4087-B272-557C1C6D0A07} 

<?xml version="1.0"?>
<ApplicationEntrySerializer xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Items>
    <ApplicationUninstallerEntry>
      <DisplayName>Microsoft Flight Simulator X Demo</DisplayName>
      <BundleProviderKey>b98a34c0-a6a2-4087-b272-557c1c6d0a07</BundleProviderKey>
      <DisplayIcon>C:\WINDOWS\Installer\{B98A34C0-A6A2-4087-B272-557C1C6D0A07}\ARPPRODUCTICON.exe</DisplayIcon>
      <DisplayVersion>10.0.60905</DisplayVersion>
      <EstimatedSize>1280529</EstimatedSize>
      <InstallDate>2019-11-27T00:00:00</InstallDate>
      <InstallLocation>E:\Program Files (x86)\Microsoft Games\Microsoft Flight Simulator X Demo</InstallLocation>
      <InstallSource>D:\TEMP_W~1\WZSE0.TMP</InstallSource>
      <Is64Bit>X86</Is64Bit>
      <IsProtected>false</IsProtected>
      <IsRegistered>true</IsRegistered>
      <IsOrphaned>false</IsOrphaned>
      <IsUpdate>false</IsUpdate>
      <IsValid>true</IsValid>
      <IsWebBrowser>false</IsWebBrowser>
      <Publisher>Microsoft Game Studios</Publisher>
      <RatingId>InstallShield_{B98A34C0-A6A2-4087-B272-557C1C6D0A07}</RatingId>
      <RegistryKeyName>InstallShield_{B98A34C0-A6A2-4087-B272-557C1C6D0A07}</RegistryKeyName>
      <RegistryPath>HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\InstallShield_{B98A34C0-A6A2-4087-B272-557C1C6D0A07}</RegistryPath>
      <SystemComponent>false</SystemComponent>
      <UninstallerFullFilename>C:\PROGRA~2\COMMON~1\INSTAL~1\Driver\11\INTEL3~1\IDriver.exe</UninstallerFullFilename>
      <UninstallerKind>Unknown</UninstallerKind>
      <UninstallerLocation>C:\Program Files (x86)\Common Files\InstallShield\Driver\11\Intel 32</UninstallerLocation>
      <UninstallString>C:\PROGRA~2\COMMON~1\INSTAL~1\Driver\11\INTEL3~1\IDriver.exe /M{B98A34C0-A6A2-4087-B272-557C1C6D0A07} </UninstallString>
    </ApplicationUninstallerEntry>
  </Items>
</ApplicationEntrySerializer>

**Comment by nico92GitHub** [comment]
Afterwards, if you have a moment:
Why is BCU looking to ping after they leave? See the 2 screen shots,
![ScreenShot_005](https://user-images.githubusercontent.com/22394276/73217655-9d49ac00-4158-11ea-85dc-888aad8d8c92.jpg)
![ScreenShot_006](https://user-images.githubusercontent.com/22394276/73217660-a0dd3300-4158-11ea-9379-244ed285f355.jpg)

 please.

**Comment by Klocman** [comment]
Looks like the Flight Simulator is doing some weird things with its
installer/uninstaller, did you try restarting your PC to see if anything
changed? As far as BCU can see based on what you pasted some part of Flight
Simulator might be running at startup for some reason.

The destination IP of 127.0.0.1 means it does not access internet, this is
the address of your local system and many applications use it to
communicate with each other. The firewall shouldn't filter this traffic
since it can cause strange issues.

**Comment by nico92GitHub** [comment]
Thank you for your answers.
For the address 127.0.0.1, I allowed access since it is for BCU.
I do not have good network knowledge, but I have retained that 127.0.0.x is the address of my machine locally. 
But what surprised me is that BCU is the only software that requests "this access" "when leaving".
A last test to validate something?

For Flight Simulator (which is rather old, but works well), I don't have any trace of it every time I start up my machine. It was BCU that showed me it existed.
I changed the installation directory and I wonder if this change is not the cause of a disarrangement after?
Or maybe BCU sees an old installation, which took place before the one now?
???

**Comment by Klocman** [comment]
I just took a second look and it looks like the flight simulator installed its own driver, that might be what gets picked up by BCU. The 127.0.0.1 access is probably a part of the code that make sure only one instance of BCU can run at one time.

It looks like everything is working as it should so I'll close this issue.
