### ISSUE TITLE
startIndex exception when loading uninstaller

### ISSUE THREAD

**Issue by yashgorana** [Klocman/Bulk-Crap-Uninstaller#252]
Getting this exception every time start BCU or click on "Reload Uninstallers"

![image](https://user-images.githubusercontent.com/11070218/75805673-457e1080-5da8-11ea-8a9e-79dda115d6df.png)

```
System.ArgumentOutOfRangeException
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.String.IndexOf(Char value, Int32 startIndex, Int32 count)
   at UninstallTools.Factory.ScoopFactory.GetUninstallerEntries(ListGenerationCallback progressCallback)
   at UninstallTools.Factory.ApplicationUninstallerFactory.GetMiscUninstallerEntries(ListGenerationCallback progressCallback)
```

Seems like an exception w.r.t scoop uninstaller entries.
OS: `Windows 1909 (OS Build 18363.657)`
BCU Version: `4.16.0.38993`
Current Scoop version:
`a9fa775d (HEAD -> master, origin/master, origin/HEAD) chore(buckets.json): Update scoop-nonportable URL (#3776)`
'extras' bucket:
`33b99063 (HEAD -> master, origin/master, origin/HEAD) rambox-pro: Update to version 1.3.0`
'main' bucket:
`93b1f754 (HEAD -> master, origin/master, origin/HEAD) kotlin: Update to version 1.3.70`

**Comment by Klocman** [comment]
Can you send me the output of `scoop export` command?

**Comment by yashgorana** [comment]
```
PS C:\WINDOWS\system32> scoop export                                                                                    aria2 (v:1.35.0-1) [main]
concfg (v:0.2019.03.09) [main]
dark (v:3.11.2) [main]
lessmsi (v:1.6.91) [main]
python (v:3.8.1) [main]
```

**Comment by patevs** [comment]
I am getting the same exception too.
