### ISSUE TITLE
Remove empty parent folders when removing junk

### ISSUE THREAD

**Issue by DmitriyYukhanov** [Klocman/Bulk-Crap-Uninstaller#26]
Hey, just tried to uninstall a latest trial version of the Revo Uninstaller.
After uninstallation process, it doesn't find Revo Uninstaller's leftovers at the 
`C:\ProgramData`
specifically the 
`C:\ProgramData\VS Revo Group\Revo Uninstaller Pro\revouninstallerpro.lic`
file and 
`C:\ProgramData\VS Revo Group`
folder since it has only this file inside).

**Comment by Klocman** [comment]
I believe this one should have worked, so it's more of a bug. I'll check if I can reproduce it.

**Comment by DmitriyYukhanov** [comment]
Oh, I'm so sorry! My bad, I didn't finished leftovers cleanup before reporting this.
So yeah, it deletes folder `C:\ProgramData\VS Revo Group\Revo Uninstaller Pro` just fine.

Though, it leaves empty folder `C:\ProgramData\VS Revo Group` after cleanup, would be nice to iterate all parent folders and remove them if they are empty.

**Comment by Klocman** [comment]
No problem. Deleting empty folders does sound like a good suggestion.
