### ISSUE TITLE
Suggest to launch Chinese version

### ISSUE THREAD

**Issue by huohua1** [Klocman/Bulk-Crap-Uninstaller#263]
first of all I apologize to you. My English is not very good. So my statement may be wrong, I am very sorry. I am a Chinese user. When I found your software, I fell in love with it. I found it to be very easy to use compared to geek. I recommended this software to my Chinese friends. But their English is not good. They can't understand this software, can your company develop a Chinese version? Because this app does not have Chinese, it cannot be promoted well in mainland China. And many people do not know the software. I hope you can launch the Chinese version here. thank you very much.

**Comment by PotoTan** [comment]
You can apply for the translation volunteer program

**Comment by tipek360** [comment]
If you open file [CONTRIBUTING.md](https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/master/CONTRIBUTING.md) you will find small manual how to contribute in translating this fantastic program. So yes there is the way how community can make translations of this application.

**Comment by Klocman** [comment]
Unfortunately I know no Chinese and I'm a single guy so I don't have the resources to manage a translation myself. If you want to help translate BCU to Chinese, please check the contributing file mentioned above.

**Comment by Klocman** [comment]
Should be solved by https://github.com/Klocman/Bulk-Crap-Uninstaller/commit/9a4f7942309a93df35ed52a31eb2d0364d4d1444
