### ISSUE TITLE
Switch to SHA256 code signing

### ISSUE THREAD

**Issue by ofer-dev** [Klocman/Bulk-Crap-Uninstaller#267]
Hey, thanks for this great software, it's really nice to have uninstallation tool that's open source and not packed with adware.
Since there are practical(ish) breaks for sha1, could you sign the next releases with sha256.

https://shattered.io/
https://sha-mbles.github.io/

Thanks

**Comment by Klocman** [comment]
Thank you for letting me know, next release will be signed with SHA256.
