### ISSUE TITLE
I want to translate the application in the romanian langwage

### ISSUE THREAD

**Issue by Talpaiute** [Klocman/Bulk-Crap-Uninstaller#271]
Where can I find language files?

**Comment by andrei-inc** [comment]
I believe you can find it at:
```Bulk-Crap-Uninstaller/source/BulkCrapUninstaller/Properties/```

**Comment by tipek360** [comment]
If you open file [CONTRIBUTING.md](https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/master/CONTRIBUTING.md) you will find small manual how to contribute in translating this program.

**Comment by Klocman** [comment]
Closing stale issue.
