### ISSUE TITLE
Uninstall list

### ISSUE THREAD

**Issue by rashxxl** [Klocman/Bulk-Crap-Uninstaller#273]
How to create an uninstall list with the extension .bcul ?

**Comment by Sulquendi** [comment]
Hello ! 

Same needs here... I'd like to use BCU in unattended mode and some documentation about the .bcul file format would be great !

Thanks

**Comment by peripatew** [comment]
Same.  I'm going a bit mad trying to track down how to find this?  Help!

@Klocman

**Comment by Klocman** [comment]
Save it from the [uninstall list editor](https://htmlpreview.github.io/?https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/master/doc/BCU_manual.html#__RefHeading___Toc343_1601368371).
