### ISSUE TITLE
Lacks windows apps

### ISSUE THREAD

**Issue by Chaython** [Klocman/Bulk-Crap-Uninstaller#277]
Any "Xbox" game I've downloaded doesn't show in BCU.

**Comment by jiggie42** [comment]
Make sure Windows Store Apps is checked under Settings -> Detection
it detects all installed Windows Store games on my machine
If you're still having trouble, please double check you're on the latest version.

**Comment by Klocman** [comment]
Tested and uninstalling games installed through the Xbox app works fine. Try resetting your config or making a clean install of BCU.
