### ISSUE TITLE
Can't check for updates

### ISSUE THREAD

**Issue by brij1234** [Klocman/Bulk-Crap-Uninstaller#279]
![image](https://user-images.githubusercontent.com/9251787/108945788-3d5b5880-762b-11eb-9ebb-6e9f9f7459f4.png)
![image](https://user-images.githubusercontent.com/9251787/108945958-a17e1c80-762b-11eb-87cd-40f2ac3f2b0b.png)

**Comment by 0lm** [comment]
Im just commenting so you dont need to worry: I cant update either, so nothing is wrong with your firewall/internet. It seems to be an error with the bcuninstaller servers.

**Comment by Dustyn69** [comment]
Good to see there are others here with this issue.

Is there any update in regards to this issue?

**Comment by farag2** [comment]
Seems the project is dead...

**Comment by lupinehorror** [comment]
the update checker hits raw.githubusercontent.com ok but doesn't find what it is looking for seemingly

**Comment by Klocman** [comment]
Fixed in the [NET-5-conversion]( https://github.com/Klocman/Bulk-Crap-Uninstaller/tree/NET-5-conversion) branch.

It's not fixable in the old version because .NET 3.5 doesn't support the encryption standard that GitHub now enforces.
