### ISSUE TITLE
Give Startup Manger it's own shortcut

### ISSUE THREAD

**Issue by brian6932** [Klocman/Bulk-Crap-Uninstaller#284]
I personally use the Startup manager tool a lot, more than BCUninstaller itself, and I think it would be pretty useful to be able to use it standalone from BCUninstaller, without having to wait for BCUninstaller to run and startup. I don't know if it's possible, but it would be really useful imo.

**Comment by brian6932** [comment]
@Klocman Which executable directly opens startup manager? Or if it's a shortcut, how do I make it's shortcut? Cause I can't find it

**Comment by ManlyMarco** [comment]
Check the manual, you need to call bcuninstaller.exe with the correct command line argument. You can create a shortcut and add the argument to it.

**Comment by Klocman** [comment]
It's `BCUninstaller.exe /sm`, make sure the shortcut points to BCUninstaller.exe inside of the win-x64 folder (or the 32bit folder if your system is 32 bit).

**Comment by brian6932** [comment]
![image](https://user-images.githubusercontent.com/18603393/118887141-ef6f8d00-b8c7-11eb-9a49-42ad099820fc.png)
@Klocman I tried this, however, it just launched normally, did I do something wrong?

**Comment by brian6932** [comment]
Oh it works, nice, is there a way to make it into a .lnk?
