### ISSUE TITLE
Malwarebytes flags BCUninstaller as malware. False positive?

### ISSUE THREAD

**Issue by Rawh** [Klocman/Bulk-Crap-Uninstaller#286]
Greetings,

This morning MalwareBytes detected issues on my system and wanted to quarantine a few applications to make my pc great again.

According to MWB two executables from BCU are malware, as seen in the picture below. 
![image](https://user-images.githubusercontent.com/10486655/116974134-ea062600-acbd-11eb-931d-ebd01c6af293.png)

Both links for the malware end up redirecting me to https://blog.malwarebytes.com/detections/malware-ai/.

Can anyone confirm these are false positives? Should I do something in regards to poking MWB telling them it's no malware or can BCU officials poke them about it?

**Comment by Klocman** [comment]
Any sort of AI detections are usually false positives. As the page you linked states, it didn't find any known malware, only triggered because of the neural net(?) detecting something it didn't like. When unsure always check the files on https://www.virustotal.com
