### ISSUE TITLE
msvcp140.dll and vcruntime140.dll was not found, for Bulk Crap Uninstaller 5.0 Portable

### ISSUE THREAD

**Issue by candrapersada** [Klocman/Bulk-Crap-Uninstaller#291]
why msvcp140.dll and vcruntime140.dll was not found?
Bulk Crap Uninstaller 5.0 Portable
Windows 10 Home

**Comment by soryanspy** [comment]
Helped to install `x86: vc_redist.x86.exe` from here [Visual C++ downloads](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0)

**Comment by Klocman** [comment]
Can you test if this an issue when starting `win-x64\BCUninstaller.exe` directly instead of BCUninstaller.exe in the root directory?

**Comment by candrapersada** [comment]
> 
> 
> Can you test if this an issue when starting `win-x64\BCUninstaller.exe` directly instead of BCUninstaller.exe in the root directory?

there is no problem with `win-x64\BCUninstaller.exe` without `x86: vc_redist.x86.exe` but why does it happen to `BCUninstaller.exe`

**Comment by Klocman** [comment]
Can you check if this build works fine without the redist?
[BCUninstaller.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/6488215/BCUninstaller.zip)

**Comment by candrapersada** [comment]
yes this build works fine without the redist

**Comment by candrapersada** [comment]
yes this build works fine without the redist

**Comment by ardee00** [comment]
Thank you for the response!  Unfortunately, the installer for that version won’t even start on my PC.  (I do have all the Microsoft redeistributables installed.)
