### ISSUE TITLE
Translation update

### ISSUE THREAD

**Issue by Kommprog** [Klocman/Bulk-Crap-Uninstaller#292]
Hello, 
I made tons of corrections in the old Russian translation and updated it according to the current v.5, but @Klocman's site is down now (at least, from Russia), so it's impossible to use feedback form for sending.

[Localisation_Pack_5.0.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/6505404/Localisation_Pack_5.0.zip)

**Comment by Klocman** [comment]
Thank you for the update. You can send updates here, it's easier to manage.
