### ISSUE TITLE
Version 5.0 gives groups in list too much whitespace around them

### ISSUE THREAD

**Issue by DarkwaterV3** [Klocman/Bulk-Crap-Uninstaller#293]
Hi Klocman,

Starting with version 5.0, the groups in the list view have large whitespaces above and below them, severely limiting how many programs can be seen in the list at once. I doubt this is intentional and I find it to be a bit of a hindrance.

In case this is relevant, I'm running Windows 10 21H1, 125 percent desktop scaling but the problem persists when I let BCU handle scaling itself.

Screenshot enclosed.

![bcu](https://user-images.githubusercontent.com/15906806/119660684-d028b080-be2f-11eb-9230-9c938ad63a6b.png)

PS love the app to bits; I believe I've already donated and if not, I will.

**Comment by Klocman** [comment]
Turns out this is a bug in winforms, it has been fixed here but not yet released https://github.com/dotnet/winforms/pull/5089
Whenever the .NET winforms 6.0 stable is released this will be fixed after updating the libraries.

**Comment by DarkwaterV3** [comment]
Many thanks!

**Comment by DarkwaterV3** [comment]
Solved as of 5.2. Thanks.
