### ISSUE TITLE
No updates for same Datas

### ISSUE THREAD

**Issue by Kubaonkel010** [Klocman/Bulk-Crap-Uninstaller#296]
![!!BCUninstaller](https://user-images.githubusercontent.com/85830946/121806998-84a93b80-cc52-11eb-95fe-331f74aea059.JPG)
 the Update-manager found 6 *.exe datas who are not updated. What can i do ?

**Comment by Klocman** [comment]
I'm not sure what this is from, or what the issue is. You can get the latest version of BCU from the releases of this repository.
