### ISSUE TITLE
Uninstalling Valorant -> BCU Wants to Delete Entire Downlods Folder

### ISSUE THREAD

**Issue by GorOps** [Klocman/Bulk-Crap-Uninstaller#297]
I just Tried to uninstall Valorant with BCU and it automatically selected all contents of my entire Downloads folder to be deleted which are now gone...

https://imgur.com/a/tel3Y1c
https://imgur.com/a/1bv4D9k

It should not be trying to delete ALL contents of the Downloads folder ever....

**Comment by cyacal** [comment]
The Valorant updater downloads game updates in partitions - usually small 120mb chunks and stores them hidden in the download folder, BCU probably got confused and marked the download folder as the Valorant Updater cache folder. You can restore your downloads folder in the Recycle Bin by right clicking certain files and pressing "Restore"
