### ISSUE TITLE
Error 0xc000007b when trying to run BCUninstaller.exe

### ISSUE THREAD

**Issue by DigiOhhh** [Klocman/Bulk-Crap-Uninstaller#298]
![image](https://user-images.githubusercontent.com/37815914/124790239-4a7a4380-df4b-11eb-9b5f-5ba7f0250e7d.png)

I tried installing Microsoft Visual C++ Redistributable 2008, 2010, 2012, 2013, 2015-2019 but none of them fixed this issue. I'm pretty sure I'm missing some dependencies, and I don't understand why I should be installing random packages and restarting my laptop when this can probably be taken care of during installation. I think you should at the very least include whatever dependency it is I'm missing in the `System Requirements` list
And by the way, I do have .NET SDK installed.

```
Edition	        Windows 11 Pro
Update	        21H2
Installed on	‎7/‎6/‎2021
OS build	22000.51
Experience	Windows Feature Experience Pack 421.16300.0.3
```

**Comment by Klocman** [comment]
Try the test build from #291 
The fix is commited but wasn't released yet https://github.com/Klocman/Bulk-Crap-Uninstaller/commit/7fb88904e3bbef97dbbcbd7d6ae9f6ee3383c6f5
