### ISSUE TITLE
Cannot uninstall Steam games, SteamHelper.exe can't find Steam Apps

### ISSUE THREAD

**Issue by chappellkm** [Klocman/Bulk-Crap-Uninstaller#299]
It's currently impossible for me to uninstall Steam games. SteamHelper.exe is unable to find Steam Apps using their ID numbers, so uninstalls fail with error code 59.

[SteamHelper.log](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/6780780/SteamHelper.log)

**Comment by Klocman** [comment]
Can you run `SteamHelper.exe steam` and see if it finds the install location? Then try `SteamHelper.exe list` and see if all games are listed there.

**Comment by chappellkm** [comment]
SteamHelper.exe steam returns the proper installation location (C:\Program Files (x86)\Steam). SteamHelper.exe list only brings up id 228980, which is the Steam redistributables.

I do have my games installed on a custom location (D:\steam_games) but this is the first time I've had a problem uninstalling from there. I've gone ahead and added D:\steam_games to "custom program installation folders" under BCU to see if this would solve the problem, but no luck.
