### ISSUE TITLE
Error/crash with fresh install via Chocolatey

### ISSUE THREAD

**Issue by K0media** [Klocman/Bulk-Crap-Uninstaller#300]
This shouldn't be strictly related to Choco (I guess), but I've tried lots of ways to circumvent this situation. Even downloaded the normal installer from the repo, but no luck.

I'll record a brief screencast reproducing the issue and showing details. See below.

https://user-images.githubusercontent.com/22375465/126410069-257fc3ed-0493-468c-9036-380fad7800b4.mp4

I can give further details on this discussion if needed.

Device: HP Elitebook 840 G5
Specs:
RAM - 16 GB
SSD - NVME M.2 512 GB
Processor - Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz - 2.11 GHz
OS: Windows 10 Pro x64 21H1 - build 19043.1110

More details can be provided as soon as advise is given up in this thread.

**Comment by Klocman** [comment]
Can you send the crash report .zip file that is generated inside bcuninsaller directory after the crash? You might need to click the send button for it to get generated.

**Comment by K0media** [comment]
@Klocman, my bad, but I can't seem to find the file you've requested me in the suggested folders even after attempting to run it again and sending the crash report.

Here's something I've captured after running it:

https://user-images.githubusercontent.com/22375465/127030383-3d45957f-9f79-4221-8a8a-268934daae8a.mp4

The only file that has logs is BCUninstaller.log, but it logs only the time it is executed, nothing else than that.

Any further advise?

**Comment by Klocman** [comment]
Right, looks like there's a separate issue with the error reporting system.

What I'm interested in is the inner exception and it's stack trace, you can
see it in the detailed view of that error popup. Also send the log file.

**Comment by K0media** [comment]
@Klocman, my apologies, but I can't seem to find the verbose debugs you're talking about.

I tried to look up over the system, but nothing relevant showed up.

If there was some sort of generated zip or log file, it would much probably show up on Everything (by voidtools) right at the moment the software crashed and I attempted to send the error report.

Isn't there a verbose/debugging argument to run the program? A test build where I can try to generate these logs?

The only log file that is generated is the one I've mentioned above. No other zip files, I believe.

Does a proper tutorial to dump logs like this exist?

I know I may seem kind of dumb right now, but I'm almost sure that if it generated logs, I could see a generated/updated file on Everything software.

A few hours ago, I tried to look it up on the Event Viewer, but nothing relevant showed up there. (Or I am doing it wrong...)


If you provide me a tutorial or something that I can dump better details on this, I'll certainly share.

Btw, when you mentioned "separate issue" above, was it a GitHub issue or something else? I think I misunderstood this point.

**Comment by K0media** [comment]
@Klocman, I still need your help for this. Would you advise me how to proceed according to the last post above?

**Comment by Klocman** [comment]
Oh, sorry, I didn't get a notification. I wanted to fix the error reporting system but couldn't get to it and for got about the issue.

In the error dialog can you click on each of the exceptions in the list shown on the screenshot below, then double click on "Stack Trace" and show the full stack traces? Also show the full Message for the exceptions.
![image](https://user-images.githubusercontent.com/14913904/130638355-4ba28dc7-a902-4c54-adb1-90f9963ef7bc.png)

**Comment by Klocman** [comment]
It should be fixed in v5.2
