### ISSUE TITLE
Unable to find an entry point named 'CoDecrementMTAUsage' in 'api-ms-win-core-com-l1-1-0.dll'

### ISSUE THREAD

**Issue by Logics4** [Klocman/Bulk-Crap-Uninstaller#322]
BCUninstaller v5.1 starts up fine and can uninstall a program, but once you press "Yes" to scan for leftovers to remove, once it is done, it shows this error:

![Error part 1](https://user-images.githubusercontent.com/25278238/136712191-69b0b3db-ab56-49fe-b4cd-c66c504239b3.PNG)
![Error part 2](https://user-images.githubusercontent.com/25278238/136712203-b3524c91-06ab-4a6b-8a4b-3a802b89c2e6.PNG)

As you can see from the screenshots, I am running Windows 7 (x86, Professional edition, SP1).
The stacktrace in there is only two lines:
```
   at WinRT.Platform.CoDecrementMTAUsage(IntPtr cookie)
   at WinRT.WinrtModule.Finalize()
```
Additionally, here is [the BCUninstaller.log's contents](https://gist.github.com/Logics4/25f43717f6abc35ca72e835f499b5b0c), showing that CoIncrementMTAUsage is also missing (which I think it is relevant - the two methods seem to be related to each other when comparing the names).

Interesting thing is, this error does not freeze the UI - it pops up that second window showing it, but the program seems to be otherwise functional until I close the error window by any means (although it's annoying to have an error pop up right there).

Perhaps it is API that Windows 7 does not have? The error does mention WinRT. I don't know where BCUninstaller uses these methods in its code but it would be great if I could still use the 5.x branch on Windows 7.

**Comment by DigiOhhh** [comment]
Happening to me as well

**Comment by DigiOhhh** [comment]
if it helps: this error doesn't occur on version 5.0

**Comment by Klocman** [comment]
> Is there anywhere else besides the error dialog box, and `<BCUninstaller's installation folder>\BCUninstaller.log`, where I may find the full stacktrace? Because what I sent in the first post was what I could find in those two.

Sorry, I didn't notice that you've uploaded the log file. Everything I needed was in the log, thank you.
