### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by canonrebel04** [Klocman/Bulk-Crap-Uninstaller#327]
The feature request that I am putting in is a dark mode setting for the app. This might be hard to implement so I'm not expecting to get a response but its just an idea.

**Comment by Soumyadeep98O** [comment]
https://github.com/Klocman/Bulk-Crap-Uninstaller/issues/228#issuecomment-453836494

**Comment by Klocman** [comment]
Closing as duplicate of #228
