### ISSUE TITLE
CLI parameters for installation

### ISSUE THREAD

**Issue by github-account1111** [Klocman/Bulk-Crap-Uninstaller#347]
I would like an ability to specify installation parameters, such as Extra Languages and Custom Installation, from the command line.
This would allow winget (and other packager managers) to specify those parameters upon installation using the [`override` option](https://docs.microsoft.com/en-us/windows/package-manager/winget/install#options).

Currently there don't seem to be any override parameters in [BCU's manifest](https://github.com/microsoft/winget-pkgs/blob/master/manifests/k/Klocman/BulkCrapUninstaller/5.1.0.0/Klocman.BulkCrapUninstaller.installer.yaml).

**Comment by Klocman** [comment]
You can select which components to install with the standard innosetup command line parameters https://documentation.help/Inno-Setup/topic_setupcmdline.htm

**Comment by github-account1111** [comment]
For anyone looking, innounp is quite useful for this.
http://innounp.sourceforge.net/
