### ISSUE TITLE
Option to show leftovers with low confidence

### ISSUE THREAD

**Issue by DmitriyYukhanov** [Klocman/Bulk-Crap-Uninstaller#35]
Currently, if I uninstall app and only bad confidence leftovers are detected, leftovers cleanup window doesn't show up.
Would be nice to have an option to force leftovers window even in case when only bad confidence leftovers are found.

**Comment by Klocman** [comment]
Would an option in the settings be enough?

**Comment by DmitriyYukhanov** [comment]
Sure, it would be totally enough!

No, it's me who should thank you for creating this amazing tool, I'm glad to help you a bit to make it even more awesome!
