### ISSUE TITLE
Visual Studio and VS Code don't show up

### ISSUE THREAD

**Issue by ak1dd** [Klocman/Bulk-Crap-Uninstaller#350]
in BC Uninstaller.  They do show up in Windows Apps and features.  I don't even see the "VS Studio Installer" listed?

I am using Windows 11 if that makes any difference

**Comment by sync1211** [comment]
Where did you install Visual Studio and VSCode?

On my current install they are being listed under "Microsoft Visual Studio Code" and "Microsoft Visual Studio Installer". (Using version 5.2 portable x64)
![grafik](https://user-images.githubusercontent.com/17365446/154814863-e312d90b-b257-4b5b-abee-824b34f0d509.png)

**Comment by Klocman** [comment]
They appear for me as well. Make sure that no filters are hiding it.

W11 might cause some issues (I don't use it so I can't test), but it is unlikely to be the cause here.

**Comment by github-account1111** [comment]
@Klocman experiencing the same issue. Could it be due to Microsoft deciding to put the whole thing in AppData\Local\Programs by default?
