### ISSUE TITLE
can i donate for you to keep maintaining this project its the 34th app i download in my list of must haves also could you add a bunch of other github apps

### ISSUE THREAD

**Issue by XxnittanixX** [Klocman/Bulk-Crap-Uninstaller#351]

**Comment by Klocman** [comment]
Sorry, it's a time issue for me, I have a ton of other projects that I want to focus on. I'll still do basic maintenance like merging PRs and fixing critical bug, so no need to worry about that.

If you want any new features, I suggest giving it a try yourself, it's really not as hard as you'd expect to program in C#.
