### ISSUE TITLE
Windows 10 bug [System.ComponentModel.Win32Exception]

### ISSUE THREAD

**Issue by purple-emily** [Klocman/Bulk-Crap-Uninstaller#353]
```
System.ComponentModel.Win32Exception
The system cannot find the file specified
Boolean StartWithCreateProcess(System.Diagnostics.ProcessStartInfo) @ System.Diagnostics.Process
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at UninstallTools.Factory.ScoopFactory.RunScoopCommand(String scoopArgs)
   at UninstallTools.Factory.ScoopFactory.GetUninstallerEntries(ListGenerationCallback progressCallback)
   at UninstallTools.Factory.ApplicationUninstallerFactory.GetMiscUninstallerEntries(ListGenerationCallback progressCallback)
BCUninstaller.dll [5.2.0.0]
1.2.0.0
24/02/2022 10:52:47 AM
5.0.13

NativeErrorCode: 2
ErrorCode: -2147467259
HResult: -2147467259
```

This is a fresh install. This happens on launch.

**Comment by zbalkan** [comment]
IS it possible that you might have leftovers from previously installed Scoop? Because if you get this error, it means the code path has found something in the places in the GetScoopInfo() method and then return true for ScoopIsAvailable. But when it comes to running it, BCU could not find the scoop in the path.

It is also possible to add a File.Exists(_scoopUserPath) but to me, it is an edge case to handle for Scoop, not for BCU.

``` cs
private static bool ScoopIsAvailable
        {
            get
            {
                if (!_scoopIsAvailable.HasValue)
                {
                    _scoopIsAvailable = false;
                    GetScoopInfo();
                }
                return _scoopIsAvailable.Value;
            }
        }

        private static void GetScoopInfo()
        {
            try
            {
                _scoopUserPath = Environment.GetEnvironmentVariable("SCOOP");
                if (string.IsNullOrEmpty(_scoopUserPath))
                    _scoopUserPath = Path.Combine(WindowsTools.GetEnvironmentPath(CSIDL.CSIDL_PROFILE), "scoop");

                _scoopGlobalPath = Environment.GetEnvironmentVariable("SCOOP_GLOBAL");
                if (string.IsNullOrEmpty(_scoopGlobalPath))
                    _scoopGlobalPath = Path.Combine(WindowsTools.GetEnvironmentPath(CSIDL.CSIDL_COMMON_APPDATA), "scoop");

                _scriptPath = Path.Combine(_scoopUserPath, "shims\\scoop.ps1");

                if (File.Exists(_scriptPath))
                {
                    if (!File.Exists(PathTools.GetFullPathOfExecutable("powershell.exe")))
                        throw new InvalidOperationException(@"Detected Scoop program installer, but failed to detect PowerShell");

                    _scoopIsAvailable = true;
                }
            }
            catch (SystemException ex)
            {
                Console.WriteLine(ex);
            }
        }

```

**Comment by purple-emily** [comment]
I have scoop installed. It exists.

The environment variable is set: `SCOOP                          C:\Users\Emily\scoop`

The `shims\\scoop.ps1` file exists. I don't know why this is erroring.

**Comment by zbalkan** [comment]
This looks like a Heisenbug. I installed scoop for this. Installed yara with scoop for testing and uninstalled it via BCU. No error. Can you provide steps for reproducing -that might be important?

**Comment by purple-emily** [comment]
I have reinstalled scoop. I have reinstalled BCUninstaller. I have installed BCU through scoop itself, and manually. No improvement.

I don't know how to reproduce this. I have set both environment variables, just incase.

I'm happy to try anything to help debug this, but I don't know where to start.

**Comment by Klocman** [comment]
@purple-emily Can you check if running `powershell.exe` works from the Run dialog (Win+R)?

**Comment by Klocman** [comment]
Can you try using this build? If the issue is with powershell not being in PATH then it should fix it. [UninstallTools.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/8648523/UninstallTools.zip)

**Comment by purple-emily** [comment]
> Can you try using this build? If the issue is with powershell not being in PATH then it should fix it. [UninstallTools.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/8648523/UninstallTools.zip)

Perfect!! It works!

I dont know what you did but that solved it.
