### ISSUE TITLE
[Suggestion] SYSTEM privilege for BSUninstaller

### ISSUE THREAD

**Issue by VoltaVX** [Klocman/Bulk-Crap-Uninstaller#356]
This may seem slightly excessive for BCUninstaller's use, but it should still be an option at the very least for those that know what they're doing it. I recently used this software to uninstall Microsoft Teams, but when cleaning up residual files, I got an error that stated deleting a given folder required SYSTEM privileges. I'm sure there must be a lot of pesky built-in apps that have SYSTEM privileges, and as such, this should be an addition that could very well help a lot of people out. While it may not do much for the everyday user, it could be a godsend for power users or sysadmins.

**Comment by rfbeck** [comment]
Run BC Uninstaller with a freeware app called "PowerRun" found on Sordum.org. You'll get BC Uninstaller running with SYSTEM (and TrustedInstaller) privileges. Use with caution!
(you can uncheck TrustedInstaller, and just it run under "just" SYSTEM privileges if you're nervous). 
note: I have experience with "PowerRun" only, but I am not its author or endorser.

**Comment by exoosh** [comment]
Simply use psexec from the Sysinternals Suite to the same effect.

However, chances are that this isn't needed and instead the "take ownership" privilege could be activated (admins have it), then ownership taken of the item(s) to be removed and then DACLs set accordingly to provide necessary delete access. After that deletion is possible without _being_ or _becoming_ `NT AUTHORITY\SYSTEM`.

**Comment by Klocman** [comment]
I thought about this before (#81) but I decided against it because of the potential damage that can be done if used by an inexperienced user. Your best bet is the walkaround of running BCU as a different user that was mentioned above.
