### ISSUE TITLE
Not installing on Windows XP Professional SP3 x86

### ISSUE THREAD

**Issue by Verwelkt** [Klocman/Bulk-Crap-Uninstaller#357]
The x86 version is still supported, right? Am I just looking in the wrong place?

**Comment by Klocman** [comment]
If you want to use BCUninstaller on Vista or older, check the [legacy 4.x branch](https://github.com/Klocman/Bulk-Crap-Uninstaller/tree/legacy-4.x) or download the latest available 4.x release.
