### ISSUE TITLE
VLC Media Player Not on List of Uninstallers

### ISSUE THREAD

**Issue by AllanHigdon** [Klocman/Bulk-Crap-Uninstaller#358]
I started trying out BC Uninstaller today (3/7). The only issue I've noticed is it won't detect VLC Media Player. Now, this should be one of the unregistered apps, because I set it up with no registry entries.

**Comment by Klocman** [comment]
If it's extracted to an unusual directory then BCU won't be able to find it. It looks for directories like "Applications" on drive roots and in directories other applications are installed to.

**Comment by AllanHigdon** [comment]
It's located in C:\Program Files\VideoLAN\VLC.
If I'm not mistaken, this is the default directory for VLC.
Shouldn't BCU be able to find it in that directory?
