### ISSUE TITLE
IObit Uninstaller junk being detected wrongly

### ISSUE THREAD

**Issue by DmitriyYukhanov** [Klocman/Bulk-Crap-Uninstaller#36]
Would be nice to have an option to somehow tune \ adjust the confidence sensitivity.
E.g. when uninstalling IObit Uninstaller, I'd like to assume all items with IObit or IObit*Uninstaller in their names are safe to delete, so here:
![image](https://cloud.githubusercontent.com/assets/883587/21703807/c41aeadc-d3c5-11e6-9295-41bd3995298b.png)
I'd have "good" confidence level for the C:\Users\*\AppData\Roaming\IObit folder.

**Comment by DmitriyYukhanov** [comment]
BTW at the `C:\Users\*\AppData\Roaming\IObit\` there is 
`C:\Users\*\AppData\Roaming\IObit\IObit Uninstaller` folder which wasn't selected for leftovers removal.

**Comment by Klocman** [comment]
`C:\Users\*\AppData\Roaming\IObit\IObit Uninstaller` Should have been detected, looks like a bug.
