### ISSUE TITLE
[Suggestion] Use winget to query Microsoft Store applications

### ISSUE THREAD

**Issue by zbalkan** [Klocman/Bulk-Crap-Uninstaller#363]
Instead of StoreAppHelper to query Microsoft Store applications, you can use winget. You can also use the PowerShell module [Winget tools](https://github.com/jdhitsolutions/WingetTools) as a starting point since it includes parsers already. Removing code is better than adding.

P. S. Winget includes all applications but starting small with just the Microsoft Store applications seemed wise.

**Comment by Klocman** [comment]
The issue is that it's only supported on recent versions of Windows (Windows 10 1709 or later), and it's not installed by default on all systems. Because of this it's not practical to switch to it for now.

**Comment by zbalkan** [comment]
Well, there might be a better way soon. They [will open source some of the the APIs](https://devblogs.microsoft.com/ifdef-windows/the-journey-of-moving-from-cpp-winrt-to-csharp-in-the-microsoft-store/) to access the store. Then, it would be easier to just get the information directly from the Store backend.
