### ISSUE TITLE
Rename nuke option to something more considerate

### ISSUE THREAD

**Issue by Wallby** [Klocman/Bulk-Crap-Uninstaller#367]
Having read personal accounts of people who witnessed an actual nuclear attack I strongly recommend to rename the "nuke option" to something more considerate, e.g. target w. a reticle icon..

![image](https://user-images.githubusercontent.com/13614975/162224103-72b4df0c-b09d-407b-b55f-1feb4460eb00.png)

**Comment by Klocman** [comment]
Feel free to make a PR with this change.
