### ISSUE TITLE
Leftovers scan skips some unique items for specific software

### ISSUE THREAD

**Issue by DmitriyYukhanov** [Klocman/Bulk-Crap-Uninstaller#37]
Some software creates different files and keys without appropriate name, to hide them from users, e.g. for the sensitive licensing data storage.

Would be nice to be able to add such items to some kind of the unique junk file database.
E.g. Wise Program Uninstaller creates two folders at the C:\ProgramData:
Isolated Storage (with 7ED43AF4\59FD041E file inside) and ProductData (with StatCache.db and un6Stat.ini files inside).

Those look like licensing-specific stuff, and would be nice to somehow detect and remove them with uninstalled program.

Maybe only hand-crafted database of such specific cases can help here, not sure it's possible to automate this somehow.

**Comment by Klocman** [comment]
That's essentially what #2 is. Ideally BCU would scan for changes and report them automatically, but honestly it's all a lot of work for little return.

Maybe items from Isolated Storage could be somehow linked to applications?

**Comment by DmitriyYukhanov** [comment]
> Ideally BCU would scan for changes during installations and report automatically, but honestly it's too much work for too little return.
Yes, this is totally understandable and I personally do not like this approach (track the installation changes), also some software generate files on the first run, not at the installation.

> Maybe items from Isolated Storage could be somehow linked to applications?
I'd be glad to know! But I didn't found anything good after few mins of googling. Maybe I missed something.

Yeah, having #2 would be nice!

**Comment by Klocman** [comment]
As it turns out it's very hard to link anything from IsolatedStorage to applications. The only way to do it, is to write an option in the application itself, so it's not viable to delete these.

ProductData folder is only created by IOBit as far as I know, but there's simply no way to link these two with good confidence. I would nag the IOBit guys to remove these during uninstallation instead.

**Comment by DmitriyYukhanov** [comment]
Fair, looking forward for any news on #2 so we could define custom uninstallation rules for such software.
There are lots of other software (including unsupported and outdated) who creates similar unique garbage and keeps it after regular uninstallation unfortunately.
