### ISSUE TITLE
Translation - Feedback and checks

### ISSUE THREAD

**Issue by bovirus** [Klocman/Bulk-Crap-Uninstaller#375]
@Klocman 

Hi.

I found somes issues in translation. Please check in screenshoots.

**File: BeginUninstallTaskWizard**

![image](https://user-images.githubusercontent.com/1262554/169690072-86dbb08b-8720-4b1e-a886-d63b613f8a8a.png)

In this file there soem strings in italian file that are empty in amster.
What's the matter?

**File: FirstStartbox**

![image](https://user-images.githubusercontent.com/1262554/169690122-cbd2e98d-2edf-47cd-a77d-f2e045612245.png)

What's the emaning of untranslated highlighte area?

**File: ListLegendWindow.hu.resx**
Whats' tehs cope of this file (no other langues availble) if ListLegendWindow.resx not contains styrings to trabnslate?

**Comment by bovirus** [comment]
Other issues

![image](https://user-images.githubusercontent.com/1262554/169767757-a9387d85-719f-4270-a4f6-1a75ad6bcd79.png)

Meaning of "unescape"?

![image](https://user-images.githubusercontent.com/1262554/169767916-cf372bde-b146-40da-b8a3-cfefaa5d07e5.png)

No original string but translation available

**Comment by Klocman** [comment]
If the original value is missing that means the application no longer uses this text, maybe it was moved or is was longer needed. It can be safely removed from translations.

The `ulk crap uninstaller` should be left as it is, it's the logo from the first start wizard.

Unescape: https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.unescape?view=net-6.0

Overall looks like none of these are issues, so I'll close this issue.
