### ISSUE TITLE
[Enhancements] InnoSetup installer for BCU (and some bugs in the original installer)

### ISSUE THREAD

**Issue by Wilenty** [Klocman/Bulk-Crap-Uninstaller#379]
Hello,
at the outset, all of the below screens comes form VM (Virtual Machine) with W10 x86 (32-bit).

For first I will point out some problems in the BCU-installer (https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/master/CODE_OF_CONDUCT.md), then I will show some improvements.

---

Bugs/problems in the BCU-installer:

1: If you use different font scaling, for example I used 150%, then the original BCU-installer looks like this (repack on the right-side):

![02-ChoosePage](https://user-images.githubusercontent.com/61757638/171054233-45f2afdd-da93-45d3-a18d-356f8d179280.png)

2: If you use default install type and then go back (via the license-page) and you will choose the portable (extraction), and again you will back (via the license-page) to choose the installation then the install path will be for the portable (extraction - no change)

2.1: Information about showing/checking the license was discussed there: https://groups.google.com/g/innosetup/c/WbnHSqRNPTw/m/ojIqR23GEQAJ

3: You can't choose the portable on the chose-install page via command-line parameters

4: The BCU-installer does not shows the sizes of install/extract (repack on the right-side):

![03-Install](https://user-images.githubusercontent.com/61757638/171054245-35d4b148-edb4-41f4-9bb7-5fec505f56d6.png)

5: BCU should remove all/most left-over reg-keys/files of the installed programs, but your installer lefts some of the BCU files after uninstall...

---

What I changed?

1: Moved the choose-page after the license-page, so now you don't need to "jump over it" to change the install-type.

2: Divided the choose-install type page into two similar parts, so now it shows whole text of the description. Also, I added the option to "click on the description to change the install-type" (blue text), but this changes can be reverted, or changed depends of author needs:

![02-ChoosePage](https://user-images.githubusercontent.com/61757638/171054233-45f2afdd-da93-45d3-a18d-356f8d179280.png)

3: Repack of BCU is showing the install-size of the components to install, and it allows to choose components of portable extraction depends of the user needs (in some way):

![03-Install](https://user-images.githubusercontent.com/61757638/171054245-35d4b148-edb4-41f4-9bb7-5fec505f56d6.png)

(Portable extraction default)

![04-Portable1](https://user-images.githubusercontent.com/61757638/171054260-717cdac7-de71-44e1-9a63-c028ff30a537.png)

(Portable extraction full)

![05-Portable2](https://user-images.githubusercontent.com/61757638/171054279-41d316f6-3250-465a-8a59-57c8e7aa5060.png)

4: Disabled the Quick-Launch task from Windows 7 and up:

![06-QuickLaunch](https://user-images.githubusercontent.com/61757638/171054286-e59e10aa-7078-4059-90e4-09b2b46ade7a.png)

5: Added option to remove BCU.settings at the uninstall (for now the message is in the English language only)

6: some other minor changes...

![07-ReadyToInstall](https://user-images.githubusercontent.com/61757638/171054299-7adddab1-a070-480b-8d66-e166977b7901.png)

---

Please check the repack of your installer with my modifications, and if you like the changes done by me - I will share the source of my modifications for BCU. But, before your agreement - there's no need to share the source scripts with my modifications.

Otherwise please tell me that you don't like the changes done by me, and please close this issue.

https://github.com/Wilenty/BCUninstaller/releases/tag/v5.3

BTW.

I also had fixed the .Net framework check for InnoSetup there: https://groups.google.com/g/innosetup/c/u3ty6tfi4Ek/m/2K_JnqSBAAAJ

And if you want to know what I am doing in the InnoSetup - check there: https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer

Best regards,
Wilenty

**Comment by Klocman** [comment]
The installer could definitely use some work, but since it works it was a low priority.

The changes look fine, I'd have to see the source to see if there's any issues. Please make a PR for the changes and I'll look into merging them.

The framework check should be unnecessary now since BCU is self-contained.
