### ISSUE TITLE
Google Drive folder is detected as µTorrent installation directory if uTorrent.exe is located in it.

### ISSUE THREAD

**Issue by andrei-cb** [Klocman/Bulk-Crap-Uninstaller#381]
![image](https://user-images.githubusercontent.com/5099150/172042038-9ceb187d-f0cd-491a-8e6a-42acda69a237.png)
![image](https://user-images.githubusercontent.com/5099150/172042049-3c247a79-93f2-4ed5-bafc-b4455bc76b73.png)

**Comment by Klocman** [comment]
Are there any other applications inside that folder? It's difficult to tell if there's something special about a folder like this, is there anything special about the Google Drive folder that stands out that BCU could detect?
