### ISSUE TITLE
.Ink

### ISSUE THREAD

**Issue by Grentari** [Klocman/Bulk-Crap-Uninstaller#382]
Unexpectedly, garbage disposal ignores labels. Deleting would be a useful functionality.

**Comment by Klocman** [comment]
What do you mean by labels? BCU does look for links that point to the uninstalled application. iirc it only looks inside start menu and desktop.

**Comment by Klocman** [comment]
It could be a number of things. If you want to look deeper into it, the shortcuts are handled here https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/c962f011eae4042951a9eb881a543b8ef1cdd314/source/UninstallTools/Junk/Finders/Misc/ShortcutJunk.cs#L20
