### ISSUE TITLE
BCU shows Steam as taking up 71GB of storage with a fresh install (no games installed)

### ISSUE THREAD

**Issue by LeoninJesterXII** [Klocman/Bulk-Crap-Uninstaller#384]
Not sure why the programs thinks the Steam client itself is 71GB, but I don't think that's accurate.

![a9a4973477705232badf239a012ceb0c](https://user-images.githubusercontent.com/34839156/174241302-89682a4e-5714-45e5-b546-62dddd041268.png)

**Comment by Klocman** [comment]
What installation location is it showing? What's the real size of the Steam folder?

**Comment by LeoninJesterXII** [comment]
> What installation location is it showing? What's the real size of the Steam folder?

The install is on C, and the total folder size is show 172 GB, now that I've installed ARK: Survival Evolved, which is a 171 GB game.

**Comment by Klocman** [comment]
So it's fixed now? What's the exact installation location shown in BCU?
