### ISSUE TITLE
Cannot remove Xbox Game UI

### ISSUE THREAD

**Issue by 44trent3** [Klocman/Bulk-Crap-Uninstaller#389]
Hi, I cannot seem to remove Xbox Game UI. I figured it might be because it's a SystemApp/protected component. However I still am interested in removing these types of packages, and I would think if the option is available even though it's "protcted" it should be possible with BCU. 

The error I get when trying to uninstall it is this:
"AppX Deployment Remove operation on package Microsoft.XboxGameCallableUI_1000.19041.1023.0_neutral_neutral_cw5n1h2txyewy from: C:\Windows\SystemApps\Microsoft.XboxGameCallableUI_cw5n1h2txyewy failed. This app is part of Windows and cannot be uninstalled on a per-user basis. An administrator can attempt to remove the app from the computer using Turn Windows Features on or off. However, it may not be possible to uninstall the app."

(Not very useful suggestion (but I presume this is Microsoft's error explanation, not BCU's), appx packages can't be turned off like that.)

**Comment by Klocman** [comment]
Hello!
It was possible for BCU to remove this package and others in the past, but after Microsoft broke the method I used twice I stopped trying to fix it. They keep making it more and more difficult to do this, and windows updates can just reinstall the removed packages anyways, so I think it's just not worth it. It's better to use ShutUp10 and lock these apps down instead.
