### ISSUE TITLE
why BCUninstaller.dll Error in Windows 7

### ISSUE THREAD

**Issue by candrapersada** [Klocman/Bulk-Crap-Uninstaller#390]
![image](https://user-images.githubusercontent.com/36833664/177569756-6a6c011b-aed8-460b-aca3-5b0a37e636dd.png)

**Comment by Klocman** [comment]
Try running windows update and install all available system updates.

**Comment by candrapersada** [comment]
> install all available system updates.

what should be installed?

**Comment by Klocman** [comment]
I don't know which update fixes it exactly, I think it was a feature update but it's easier to just let it install everything. You don't need to go up a service pack if you don't want to.

**Comment by Klocman** [comment]
I added a note about this in the wiki, and I'll close the issue. If updating didn't solve this issue, please reopen it.
