### ISSUE TITLE
telemetry enabled by default 

### ISSUE THREAD

**Issue by chirag127** [Klocman/Bulk-Crap-Uninstaller#391]
i just installed your app and found that the telemetry was enabled by default. Can you please tell me what? The telemetry includes.
![image](https://user-images.githubusercontent.com/76880977/177761134-945e5980-4350-4676-9909-0059f0be159d.png)

**Comment by Klocman** [comment]
https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/master/source/BulkCrapUninstaller/Functions/Tracking/UsageManager.cs#L149

**Comment by chirag127** [comment]
> https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/master/source/BulkCrapUninstaller/Functions/Tracking/UsageManager.cs#L149

You want me to make a pull request for disabling it by default?

**Comment by chirag127** [comment]
> You asked what the telemetry included so I linked you the place it's collected. On the first start the setup wizard will always appear and let the user disable it before any data is sent, so I don't see the issue.

But you know most of the people don't read the terms and Just click next. It's the behaviour of bad sites to enable such options by default.

**Comment by chirag127** [comment]
> https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/master/source/BulkCrapUninstaller/Functions/Tracking/UsageManager.cs#L149

What is locale ?

**Comment by Klocman** [comment]
> > https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/master/source/BulkCrapUninstaller/Functions/Tracking/UsageManager.cs#L149
> 
> What is locale ?

https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.installeduiculture?view=net-6.0

**Comment by Klocman** [comment]
Why close the issue? I think it was still valid, I'm thinking about changing it to be off by default in the future.

**Comment by chirag127** [comment]
> Why close the issue? I think it was still valid, I'm thinking about changing it to be off by default in the future.

I was really depressed, so, i just closed all my issues.
