### ISSUE TITLE
ISSUE: Valorant estimated allocated size

### ISSUE THREAD

**Issue by SicuramenteDave** [Klocman/Bulk-Crap-Uninstaller#396]
Each time when I open BCUninstaller, the estimated allocated size of Valorant is 1.53TB. I think it’s a mistake and I don’t understand how can estimate such a high dimension.
![Issue](https://user-images.githubusercontent.com/43844382/182926623-b0bc3996-81db-4228-bae3-ee9235286b0c.png)

**Comment by Klocman** [comment]
Can you post results of `File > Export data of selected unintstallers` (with only this one selected)? What's the actual size of the VALORANT folder?

**Comment by SicuramenteDave** [comment]
Yes, I posted it on [pastebin](https://pastebin.com/0Y5EChu3)

The screenshot is the actual size of the entire folder:

![image](https://user-images.githubusercontent.com/43844382/183301081-26a3a80d-f477-49a5-a7c7-1fa724609b8d.png)

**Comment by Klocman** [comment]
Can you open regedit (from Run window), navigate to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Riot Game valorant.live` (you can paste this to the address textbox), and show how the EstimatedSize value looks like? I'm guessing it was set incorrectly by whatever installed the game.

**Comment by LandarXT** [comment]
I will addd that this appears to not be an issue with this program: looks like it was also noted [in this reddit thread](https://www.reddit.com/r/VALORANT/comments/kvqnzy/anyone_else_got_a_crazy_valorant_file_size/)
