### ISSUE TITLE
UI Preferences Panel issue - V 5.4 x64 - WINDOWS 10 X64

### ISSUE THREAD

**Issue by GrosBourrin** [Klocman/Bulk-Crap-Uninstaller#399]
hello :)
First, your soft is GREAT ! keep up the good work, i love it ! And i'm french so forgive my bad english.

But i noticed an issue in the preferences panel, there's a hidden button as you can see on the pic at the ' **?** ' arrow
![BCUninstaller_1zKJMpfVT0](https://user-images.githubusercontent.com/40931468/183930011-51b1f746-a1bf-4443-a4e3-3c8e109e995a.png)

What's this button and could you fix this bug please ?
The bug persists if i uncheck "**enable dpi-aware interface scaling**" in **Interface** tab and restart BCU.
My version is Win10 x64 - BCUninstaller v5.4 x64 french language.

**Comment by Klocman** [comment]
Does this get fixed if you turn off the DPI aware settings under the Interface tab?

**Comment by GrosBourrin** [comment]
as i wrote : "The bug persists if i uncheck "**enable dpi-aware interface scaling**" in **Interface** tab and restart BCU."

**Comment by Klocman** [comment]
Does the bug still happen if you switch to the English language?

**Comment by GrosBourrin** [comment]
it's good in english version. It seems French is the problem, i didn't try other languages, 

![](https://user-images.githubusercontent.com/40931468/184568375-1b8cbd96-de55-4c32-9711-86f0bcecf9f4.png)
