### ISSUE TITLE
Fault installation on windows 11 ARM64

### ISSUE THREAD

**Issue by Corsair-63** [Klocman/Bulk-Crap-Uninstaller#400]
When tried to setup in windows 11 ARM64 version the setup program said that invalid architecture.

but it will work either in x86 version emulation either x64 via emulation too, much better this last option.

so, for setup for windows 11 ARM64 you have to choose for the portable version and copy the whole x64 folder to BCP folder of Program files and it such way it will work.

should be nice that could be installed with the setup program, for windows 10 ARM64 will be valid x86 version for latest windows 10 ARM64 developers version and windows 11 ARM64 will be valid x64 version.

but maybe I'd be asking for impossible things but really nice to have a native version compiled for windows ARM64 🤩😶‍🌫️

**Comment by Klocman** [comment]
Does the launcher work in the portable version (starts the correct bit version)? If the issue is only in the installer then it shouldn't be too bad to fix.

**Comment by Corsair-63** [comment]
I unzip the x64 folder/version on "Program files" and made a shortcut for the "start menu" and the program runs smoothly without any problem (win 11 ARM64).
I do not use the launcher, I use the program itself "BCuninstaller.exe" in x64 folder, I mean, I unzip the content of  x64 folder straight away in "X:\Program Files\BCUninstaller\"

**Comment by Klocman** [comment]
Can you extract the entire zip file and try running BCuninstaller.exe that's outside of the win-x64 folder? What happens then?

**Comment by Klocman** [comment]
I've compiled a test installer that might work on arm64, can you give it a try? https://pixeldrain.com/u/iPKedAtt

**Comment by Corsair-63** [comment]
Microsoft Surface Pro X
Windows 11 Pro, Version 21H2 - 22000.856

already done, extracted files in D:\BCUninstaller and run the launcher, it has been launched x64 edition.
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/76228638/184420108-3929cf95-dfbd-419b-bea8-5f1ab0ffe0df.png">
and from the tasks administrator:
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/76228638/184420493-1486581a-b83e-455b-83d1-af7a7679bbd3.png">

**Comment by Corsair-63** [comment]
> I've compiled a test installer that might work on arm64, can you give it a try? https://pixeldrain.com/u/iPKedAtt

already tested and no problem in installation, screen-shot of it.
<img width="994" alt="image" src="https://user-images.githubusercontent.com/76228638/184421809-95383f0a-c5be-4b34-9502-ddaf55388b70.png">

bear in mind that x64 version will work only in windows 11 and latest insider versions of windows 10 (ARM64).

good to see that installer is working fine in windows 11.

**Comment by Corsair-63** [comment]
Hi Marcin,

I'm in my boat 🛥️ now and I'll be at home tonight and will test the zip file and also if you tell me the arm version, and give you a feedback.

Absolutely no problem and what I could help from my side will be welcome.


Saludos, Carmelo Baquero
Outlook para Android<https://aka.ms/ghei36>
________________________________
