### ISSUE TITLE
Scoop app detection has been broken

### ISSUE THREAD

**Issue by davidxuang** [Klocman/Bulk-Crap-Uninstaller#401]
Scoop has [changed](https://github.com/ScoopInstaller/Scoop/commit/c4d1b9c22f943a810bed7f9f74d7d4d5c42d9a74#diff-d83ac0b4261ffb627685894a5ad95600470725a984e03c810b2cc3e45f5495a0) its export format to “pretty” JSON and the app detection is now failing. These changes were done on June 24 and released on July 7. I can help with updating [ScoopFactory.cs](https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/4494080365f8e41673cf1c6759847adefd1f1569/source/UninstallTools/Factory/ScoopFactory.cs), but I wonder if it is necessary to retain compatibility with old format.

**Comment by Klocman** [comment]
Ideally it should fall back to the old format if parsing JSON fails. It looks like you've done that in the PR, so that's good. Thank you for taking your time to fix this.
