### ISSUE TITLE
32bit shortcut on 64bit system

### ISSUE THREAD

**Issue by SebastienFRA** [Klocman/Bulk-Crap-Uninstaller#407]
Hello,

First of all, your software is great. 😊

I am Sébastien and I want to add BCUninstaller to my program (softwares installer), the problem I encounter is that BCU Installer does not take into account the system on which it is installed to create the shortcut.
Indeed, my program only works on 64bit systems, and using the shortcut created by BCU, I end up with an error: "invalid Win32 application" while it works very well with the 64bit application in the "win-x64" folder.
Could BCU create a shortcut to 64bit BCU on 64bit systems?

Thank you for your work 😉

**Comment by Klocman** [comment]
Uhh, sorry I don't quite understand what is happening. Do you have a 32 bit system and the installer only installs the 64 bit version? Does the portable version work?

**Comment by SebastienFRA** [comment]
Sorry if I wasn't clear. 😅
I am under Windows 64 bit. When I install BCU, the icon on the desktop and in the start menu launches the 32 bit version not the 64 bit version. This is where I get an "Invalid Win32 application" error.
When I manually launch BCU in 64 bit, in "win-x64" folder, it works fine.
I hope I was clearer

**Comment by Klocman** [comment]
Right, this error. You most likely have to run Windows Update and install any system and optional updates (most importantly C++ redistributables).
