### ISSUE TITLE
BC Unistaller display crammed up

### ISSUE THREAD

**Issue by Dr2t39** [Klocman/Bulk-Crap-Uninstaller#417]
The window display after the 5.4 update is all crammed up to the left and I can't seem to find a way to fix it, not in the view menu, not in any other place.
![Untitled](https://user-images.githubusercontent.com/116488112/197384876-8e407c86-bbf9-4c6b-8e27-5adbfd3aadd4.png)
x…]()

**Comment by Dr2t39** [comment]
Fixed it, sort of. In Settings, interface, uncheck "enable DPI-aware interface scaling". It now looks whole, but blurry, for some reason. Anyway, it's enough.

**Comment by Klocman** [comment]
You can double click on the | separators to make the columns resize themselves to fit content. You should only have to do this once, so no need to disable DPI aware scaling if this is the only issue you have (although it looks like it isn't).

What % text scaling do you have set on your display (display settings > scale and layout), and what's the resolution?
