### ISSUE TITLE
Support git repositories

### ISSUE THREAD

**Issue by myfairsyer** [Klocman/Bulk-Crap-Uninstaller#421]
Whenever everything search is being used on the host, BCU could easily search for `.git` [files](https://git-scm.com/docs/git-worktree#:~:text=made%20in%20a-,.git%20file,-located%20at%20the) and folders in order to identify whole git repositories

**Comment by Klocman** [comment]
I'm not sure how useful that would be. Repositories aren't really applications and it seems weird to treat them as such.

**Comment by myfairsyer** [comment]
That's right.
The use case I have in mind is- looking for space to free up on your system.
In that case, you'd not only look for applications.
But I guess another tool might be better suited then.
