### ISSUE TITLE
FR: Support maven (and gradle?)

### ISSUE THREAD

**Issue by myfairsyer** [Klocman/Bulk-Crap-Uninstaller#422]
Maven is a widely used build and dependency management tool, primarily used for java.
The local `.m2` repository of dependencies can grow a lot in size and whoever wants to get an overview of what takes their disk space might want to know about their local `.m2` repository as well.
There are other similar tools, like Gradle that might also be worth considering.

**Comment by Klocman** [comment]
I think this is a bit too niche of a use for BCU. Most devs will probably want to use the proper tools for managing these.

**Comment by myfairsyer** [comment]
Totally. See also my comments in #420, #421
