### ISSUE TITLE
[Feature Request] Uninstall on a double click

### ISSUE THREAD

**Issue by netizeni** [Klocman/Bulk-Crap-Uninstaller#423]
Hi, 

First, I have to say this is a great piece of the software, so thank you for making it. 

I wanted to ask, is it possible to add an option to uninstall the app on a double click? Currently, double-clicking the app in the list open its properties, while it would be nice to have an option to switch the behaviour to start uninstall process.

**Comment by Klocman** [comment]
It could be a setting I suppose.
