### ISSUE TITLE
After uninstalling 5.2 and installing 5.4 : can't start BCUninstaller. Error message screenshot attached

### ISSUE THREAD

**Issue by CynicalWilson** [Klocman/Bulk-Crap-Uninstaller#425]
![image](https://user-images.githubusercontent.com/29756616/201207606-857e1911-c5e8-4565-954b-a71e3726e8d0.png)

![image](https://user-images.githubusercontent.com/29756616/201207625-312d1153-46ab-4520-b2de-b07c73b83664.png)

![image](https://user-images.githubusercontent.com/29756616/201207838-19e2cb60-cbca-448c-9e30-feb6a07b3e14.png)

**Comment by Klocman** [comment]
Can you copy and send me the value of "Stack Trace" from the second screenshot?
