### ISSUE TITLE
Remove Windows 10 Built in Apps

### ISSUE THREAD

**Issue by candrapersada** [Klocman/Bulk-Crap-Uninstaller#428]
How to Remove All Built-in Windows 10 Apps at Once with Bulk Crap Uninstaller?

**Comment by Jon-guy30** [comment]
Look in the settings, if you have "Hide by Microsoft" unchecked it should load the default Windows programs and allow you to remove them. On my Windows 10 laptop I've removed the Store, Cortana and such programs from the computer.

I recommend double-checking so you're not removing something you do want, i.e, gamers probably want Xbox game bar, or if you buy games and stuff from the Store, probably leave it.
