### ISSUE TITLE
Way to remove all leftovers of applications that were not uninstalled with BC Uninstaller

### ISSUE THREAD

**Issue by GastonKhouri** [Klocman/Bulk-Crap-Uninstaller#429]
Is there a way to remove all remnants of applications that were not uninstalled with BC Uninstaller? 

I really love the program, I don't know if there will be any feature that allows you to remove all leftovers from programs that were uninstalled without the tool, if not, it would be a 10/10 feature.

**Comment by Klocman** [comment]
You can clean up some of it with `Tools > Clean up program files folders`. Be careful of what you remove however. To clean up left over application settings I suggest using BleachBit.
