### ISSUE TITLE
Can't install BCUninstaller on W11 Parallels VM on M1 MPB but launching the portable application works?

### ISSUE THREAD

**Issue by Heggeg** [Klocman/Bulk-Crap-Uninstaller#432]
Hello all, 

I can't install bulk crap uninstaller via chocolatey or with the native setup file from fosshub. 

It is a Windows 11 Enterprise VM running on my MacBook Pro with M1 processor. The curious thing is that I can launch the portable application without problems. 

Is this simply my bug in the installation routine? 

Setup:
<img width="1800" alt="grafik" src="https://user-images.githubusercontent.com/31763162/205974522-aab95c99-a2b5-43b5-94d8-9a566b0d4494.png">
Portable:
<img width="1800" alt="grafik" src="https://user-images.githubusercontent.com/31763162/205974378-5924801b-347d-40b9-81cf-552ae0adb902.png">

**Comment by Klocman** [comment]
Most likely related to #360 

these lines are probably causing it, but there doesn't appear to be a solution other than just removing the check completely https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/master/installer/BcuSetup.iss#L48-L49

**Comment by Klocman** [comment]
Should be resolved in v5.5, please reopen the issue if this still happens.
