### ISSUE TITLE
Dark Theme Mode

### ISSUE THREAD

**Issue by HitagiSenjougaharaFFXIV** [Klocman/Bulk-Crap-Uninstaller#437]
Hello, i love this program but please allow us to have a dark mode. The launching page WHITE is burning my eyes @ night,,,, Thank you

**Comment by pizofreude** [comment]
I second this motion.

**Comment by LewisJohnson** [comment]
I've started work on this

**Comment by Klocman** [comment]
Duplicate of #228

**Comment by Adil-Lidan** [comment]
> I've started work on this

any hope ? :)
