### ISSUE TITLE
[Junk Detection] steamapps/downloading cleanup

### ISSUE THREAD

**Issue by Alluseri** [Klocman/Bulk-Crap-Uninstaller#444]
In every game library of Steam, there's a "downloading" folder:
<img src="https://cdn.nest.rip/uploads/8bd8a212-1787-4773-8cea-b06dd10f4216.png">
<img src="https://cdn.nest.rip/uploads/dcc70875-bc62-4f77-9890-2b4b1d9565b7.png">
(*It seems that no libraries other than the Steam's "native" library have the folder used, as seen above. The game was installed into the* `.Steam Games` *library.*)

It would be great for BCUninstaller to detect leftovers of Steam games in those folders(detectable by the game ID on path `./steamapps/(game ID)`)

BCUninstaller currently detects those leftovers as part of the whole Steam package:
<img src="https://cdn.nest.rip/uploads/727dfbb4-033d-455a-b559-4c3a3c1f925e.png">
<img src="https://cdn.nest.rip/uploads/07f844b8-0230-4f7b-acd7-0622695f40a6.png">

In the best case scenario, BCUninstaller should be able to subtract and possibly separate those leftovers from the Steam package, as those are not actually Steam's leftovers and are not part of Steam as an application, obviously.

The wanted basic functionality is for BCUninstaller to delete those `downloading` leftovers along with the games when they are removed through BCUninstaller(Steam **did not** remove them automatically after removal through the game library using `SteamHelper.exe`)

**Comment by Klocman** [comment]
I added searching for junk when uninstalling steam apps, but not the other suggestion. Subtracting size is pretty messy to implement and I think the current behaviour is what's usually expected.
