### ISSUE TITLE
[Question] How did you sign BCU?

### ISSUE THREAD

**Issue by Hedreon** [Klocman/Bulk-Crap-Uninstaller#446]
I have a [password generator project I made in Java](https://github.com/Hedreon/PasswordGenerator) (a language similar to C#, and older than C# itself), and I want to sign my password generator project to reduce the amount of false positives on the compiled `.exe`, so, I'm going to ask you the following questions:

1. How did you do it?

2. Was it expensive or was it cheap?

3. If cheap, did you make it from scratch? (yes/no)

**Comment by Klocman** [comment]
https://shop.certum.eu/open-source-code-signing.html
