### ISSUE TITLE
BCUninstaller翻譯問題 - 安全性原則不允許HRESULT: 0x8013141A 錯誤/ BCUninstaller Translation Issue - Security Policy Prohibits HRESULT: 0x8013141A Error

### ISSUE THREAD

**Issue by sam00905266** [Klocman/Bulk-Crap-Uninstaller#449]
我最近嘗試使用官方推薦的Resx Translator來為BCUninstaller進行翻譯，但是在執行時經常遇到安全性原則不允許的錯誤，錯誤代碼為HRESULT: 0x8013141A。我嘗試了一些解決方案，但都沒有解決問題。我想請問是否有人能提供更多幫助和建議。
![圖片6](https://user-images.githubusercontent.com/125323096/220008959-f830220f-8804-4c22-a5ff-b64365731511.png)
---
I recently tried to use the official recommended Resx Translator to translate BCUninstaller, but I frequently encountered a security policy prohibits error with the HRESULT: 0x8013141A error code. I have tried several solutions, but none of them have solved the problem. I would like to ask if anyone can provide more help and suggestions.
---
translate by chatGPT

**Comment by Klocman** [comment]
Try removing all of the `obj` folders inside the source code. You can also turn off loading assemblies under the Settings menu. If that fails, try running the translator as administrator.

**Comment by sam00905266** [comment]
我確實嘗試過 running the translator as administrator 但並沒有效果 至於你前面提及的 我無法理解是什麼意思 你可以錄屏操作嗎 謝謝🙏
翻譯來自 iPad 內建翻譯
–––
I did try running the translator as administrator, but it didn't work. As for what you mentioned earlier, I can't understand what it means. Can you record the screen operation? Thank you🙏
Translation from iPad built-in translation

**Comment by Klocman** [comment]
Turn off loading assemblies in the Settings menu, that's the easiest fix.

**Comment by Klocman** [comment]
I'm moving the issue here so it can be fixed https://github.com/HakanL/resxtranslator/issues/78

In the meantime you'll have to turn off "Settings\Load assemblies from opened directory".
