### ISSUE TITLE
Portable BCUninstaller 5.4 making error on start - "Failed to start BCUninstaller - %1 не является приложением Win32"

### ISSUE THREAD

**Issue by ded-sergei** [Klocman/Bulk-Crap-Uninstaller#450]
Windows 7 x64. Portable BCUninstaller 5.4 (and 5.2) making error on start - "Failed to start BCUninstaller - %1 не является приложением Win32"
![BCUninstaller 5 4 Portable 2023-02-21_181248](https://user-images.githubusercontent.com/126001317/220404256-d08d58ad-8835-45ab-8e57-b437ddd9d2a5.jpg)

**Comment by Klocman** [comment]
Run windows update and install all system and .NET updates offered.

**Comment by ded-sergei** [comment]
The second method works. Thanks !

**Comment by Klocman** [comment]
Can you test if this gets fixed in v5.5? I'll release it within a day or so. If the bug still happens, please reopen this issue and send me the full path to the launcher.

**Comment by ded-sergei** [comment]
checked version 5.5 Portable. Nothing changed, still have error with 
main installer.

------ Исходное сообщение ------
От: "Marcin Szeniak" ***@***.***>
Кому: "Klocman/Bulk-Crap-Uninstaller" 
***@***.***>
Копия: "ded-sergei" ***@***.***>; "Author" 
***@***.***>
Отправлено: 03-Mar-23 20:08:51
Тема: Re: [Klocman/Bulk-Crap-Uninstaller] Portable BCUninstaller 5.4 
making error on start - "Failed to start BCUninstaller - %1 не является 
приложением Win32" (Issue #450)

**Comment by LamaLello** [comment]
installed the not portable version in D:\Program Files\BCUninstaller and faced the same error. uninstalled and reinstalled in D:\BCUninstaller and the error was gone

**Comment by Klocman** [comment]
@ded-sergei @LamaLello Can you check if this build fixes the issue?
[launcher debug.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/12742882/launcher.debug.zip)

**Comment by ded-sergei** [comment]
Debug version works OK.


------ Исходное сообщение ------
От "Marcin Szeniak" ***@***.***>
Кому "Klocman/Bulk-Crap-Uninstaller" 
***@***.***>
Копия "ded-sergei" ***@***.***>; "Mention" 
***@***.***>
Дата 27.09.2023 23:04:33
Тема Re: [Klocman/Bulk-Crap-Uninstaller] Portable BCUninstaller 5.4 
making error on start - "Failed to start BCUninstaller - %1 не является 
приложением Win32" (Issue #450)
