### ISSUE TITLE
does BCU cleans registry too?

### ISSUE THREAD

**Issue by goyalyashpal** [Klocman/Bulk-Crap-Uninstaller#460]
reference: revo uninstaller

search term: regedit

**Comment by Klocman** [comment]
Yes.

**Comment by goyalyashpal** [comment]
looking at the screenshot in the readme now, it seems that registry and files are in same panel of leftovers:

![4.png](https://github.com/Klocman/Bulk-Crap-Uninstaller/raw/11a978d18d52aad2c8960a4458a8c1000491de70/assets/4.png)
