### ISSUE TITLE
bad bug

### ISSUE THREAD

**Issue by helan-1997** [Klocman/Bulk-Crap-Uninstaller#463]
![image](https://user-images.githubusercontent.com/75832012/224328813-f06357fa-87dd-45dd-94a7-512beb801eb5.png)
do you think this name of the first software is right?

**Comment by Klocman** [comment]
I can't read any of it.

**Comment by detrophy** [comment]
He refers to the first entry of the list, where as the Icon is that of AMD, as well as the Publisher also States Advanced Micr...
This is a driver for AMD chipsets, graphics cards and such.

The name is 7-Zip, which is clearly wrong. I got the same issue.
![grafik](https://user-images.githubusercontent.com/23260830/235348750-9d456727-63e0-4f4a-926c-a3ce1bee9cf0.png)

**Comment by Klocman** [comment]
Can you export these entries and send me the resulting xml file?

**Comment by detrophy** [comment]
Here you go: [New BCUninstaller Export.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/11411655/New.BCUninstaller.Export.zip)

I can see that AMD is using the 7-Zip cli binary to extract the installer data. Which is, in a sense, correct that it's being displayed as 7-Zip Console.
