### ISSUE TITLE
msg at end of uninstallation - term in french "vestige"

### ISSUE THREAD

**Issue by nico92GitHub** [Klocman/Bulk-Crap-Uninstaller#464]
Hello Dev(s)
Your BCU project is really doing a great job! I'm a fan!:=)

I just want to make 2 observations:
1/ At the end of an uninstallation, the small window at the top right does NOT indicate that afterwards, there is the launch of the search for traces resulting from the uninstallation (unless I am mistaken, I may have missed a setting).

2/ French translation: In the window that searches for leftover items, your info text says search for "vestiges". In French, the term"vestige" is used in archaeology. It can be said with humor to say that we are looking for really, really very old elements.

Awaiting your feedback on my observations,
Nico

**Comment by Klocman** [comment]
Hello! The French translation is handled by a separate translator, I'll let them know. I'm not sure if it's intended but I'd guess it is.

**Comment by nico92GitHub** [comment]
Thank you for your return.
My observation was for the case where the humorous effect had escaped the translator.
Of course, I let the developer give the color he wants to this excellent BCU.
Nico
