### ISSUE TITLE
Cannot create restore point.

### ISSUE THREAD

**Issue by fruini** [Klocman/Bulk-Crap-Uninstaller#472]
Program Version: v5.5
OS: Windows 10

When I tried creating restore point in BCUninstaller, it doesn't create them. However, If I create restore point manually in System Properties window, it does work.

Tried reinstalling the program, restarted PC, but none of them worked.

**Comment by TheKloras** [comment]
Maybe put up a warning on the restore point step that people should create one manually while this bug isn't resolved?

**Comment by fruini** [comment]
> Maybe put up a warning on the restore point step that people should create one manually while this bug isn't resolved?

Forgot I still have this issue open, but I did manage to fix the bug by just doing fresh installation of W10, installed BCU & let it create restore points automatically, and it successfully did.
