### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by Sahil12524** [Klocman/Bulk-Crap-Uninstaller#474]
I need a dark theme support!

**Comment by Sahil12524** [comment]
public void themeChecker()
        {
            int lightmode = (int)Registry.GetValue(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "AppsUseLightTheme", "1");
            if (lightmode != 1) // Dark Mode
            {
                if (DwmSetWindowAttribute(Handle, 19, new[] { 1 }, 4) != 0)
                {
                    DwmSetWindowAttribute(Handle, 20, new[] { 1 }, 4);
                    return;
                }
                ThemeHelper.DarkTheme();
                isLightMode = false;
                memoryFreeUp();
                return;
            }
            else // Light Mode
            {
                DwmSetWindowAttribute(Handle, 19, new[] { 0 }, 4);
                ThemeHelper.LightTheme();
                isLightMode = true;
            }
            //memoryFreeUp();
            return;
        }

**Comment by Klocman** [comment]
Duplicate of #228, related to #338
