### ISSUE TITLE
possible to export list to .html instead of .xml?

### ISSUE THREAD

**Issue by nico92GitHub** [Klocman/Bulk-Crap-Uninstaller#477]
Hello Dev
Just a wish: In order to have a list of programs, visually simpler, would it be possible to output this list in .html format?
Awaiting your return,
best regards,
Nico

**Comment by Klocman** [comment]
What exactly are you looking for? A human readable table, or an analog to what's displayed inside BCU with icons, colors and such?

You can use a tool like https://www.cleancss.com/XML-to-HTML/ to generate html out of the xml file that BCU exports. You can also open it in Excel or similar (Data > XML Source).

**Comment by nico92GitHub** [comment]
Thank you for your return.

My ultimate wish would be something like below, which is a list generated by the (android) Swift Backup application:


For me human, it is visually simple to find a program with the icon and the name of the program.

Nico



What exactly are you looking for? A human readable table, or an analog to what's displayed inside BCU with icons, colors and such?

You can use a tool like https://www.cleancss.com/XML-to-HTML/ to generate html out of the xml file that BCU exports. You can also open it in Excel or similar (Data > XML Source).

**Comment by nico92GitHub** [comment]
Oops!

I tested the xml to html conversion with the site "https://www.freeconvert.com/" which does not require an account to convert.
Yes, the result is correct:



I don't have Excel but Gnumeric whose windows distribution has been stopped for a long time. The result is also correct.


Sorry to bother you, I think you can close issue #477.

Nico


What exactly are you looking for? A human readable table, or an analog to what's displayed inside BCU with icons, colors and such?

You can use a tool like https://www.cleancss.com/XML-to-HTML/ to generate html out of the xml file that BCU exports. You can also open it in Excel or similar (Data > XML Source).

**Comment by nico92GitHub** [comment]
reHello

I don't remember if I made this comment before:
The last window at the end of an uninstallation does not indicate that the next step is to search for "vestiges" in french, traces that can be removed, residues. It seems to me that it would be better to indicate this last step.
