### ISSUE TITLE
Translate language to Chinese,Traditional(zh-Hant)

### ISSUE THREAD

**Issue by Henryliu880922** [Klocman/Bulk-Crap-Uninstaller#483]
While Update the BCUninstaller, I found that you Release the language Pack, and still hasn't the Traditional Chinese Language, so I spend my time to translate it. I am Taiwanese,and I live in Taiwan,Thanks!
[Files to translate.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/11239841/Files.to.translate.zip)

**Comment by Klocman** [comment]
Thanks for the translation! I'll include it in the next release.

**Comment by Henryliu880922** [comment]
Yeah,Thanks
