### ISSUE TITLE
Problem Starting Bulk Crap Uninstaller

### ISSUE THREAD

**Issue by LuFeDuTi** [Klocman/Bulk-Crap-Uninstaller#489]
Hello, I am writing this message because it had never happened to me with the program and I want to know if there is a solution because I have reinstalled and installed it and the problem continues

The problem is that I open the program but it doesn't show up and it doesn't give an error either, what is that due to and I have everything that program needs to work as it is

I use Window 7 Ultimate X64 Bits

**Comment by Klocman** [comment]
Run Windows Update and install all available system updates.

**Comment by LuFeDuTi** [comment]
Thanks The Problem is Solved

**Comment by Klocman** [comment]
What was the issue?
