### ISSUE TITLE
Windows Defender/Security's CFA(Controlled Folder Access) prevents registry backup

### ISSUE THREAD

**Issue by Anutrix** [Klocman/Bulk-Crap-Uninstaller#502]
After an uninstall process, if we do registry cleanup with backup, Windows Defender/Security's CFA(Controlled Folder Access) prevents it and causes an error saying something like '<full_file_path> not found/specified'.

Disabling CFA and retrying works. Not sure but seems like Windows Security side problem as other software like CCleaner, Malwarebytes, etc. also seem to have same issue.

**Comment by Klocman** [comment]
I can't really do much about this, it's entirely on the user to properly configure CFA and add exclusions for things they trust. Looks like there are ways I could circumvent CFA but I'd rather not risk getting labelled as malware.
