### ISSUE TITLE
Bulk-Crap-Uninstaller

### ISSUE THREAD

**Issue by Sandman78692** [Klocman/Bulk-Crap-Uninstaller#503]
Wonderful Program, How can I "Size All Columns to Fit" & "Size Column to Fit' on BCU's GUI?!?
Also, how can I Export & Print the Installed Programs List in Various Format (txt, csv, spreadsheet etc.)?!?
Thank you.

**Comment by Klocman** [comment]
Double click on the right edge of the list headers to auto size the columns. There's no way to auto size all of the columns at the same time.
