### ISSUE TITLE
External Execute Failed

### ISSUE THREAD

**Issue by mus9irehw1ee** [Klocman/Bulk-Crap-Uninstaller#508]
I have recently just updated from v.5.5 to v.5.6. When I am tasked with items I would like to, the program would run flawless until the last deeep scan (the scan that shows you all the registries. 

I have tired to uninstall and reinstall the program, attempted to even try to use the portable version, but nothing seems to fix it. 
![BAU Uninstaller Error (System Memory Dump)](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/104021963/6ae5d040-517f-4b90-8bd3-6c031f60ab2e)

**Comment by mus9irehw1ee** [comment]
[](
![BAU Uninstaller Error (System Memory Dump)](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/104021963/5148ee6f-2109-4712-9630-6c6cf413f873)
url)

**Comment by Klocman** [comment]
Turn off execution of external applications in `Settings > External Tools`.

**Comment by mus9irehw1ee** [comment]
YAH!! thank you that worked
