### ISSUE TITLE
Two suggestions for adding files shredding and file recovery functions

### ISSUE THREAD

**Issue by NebulaTechs** [Klocman/Bulk-Crap-Uninstaller#513]
and can you support uninstall browser extensions?

**Comment by Klocman** [comment]
There are no plans for shredding or file recovery.

You can disable IE browser extensions in the start-up manager window, support for extensions in other web browsers is not planned at the moment.

Hotkeys are shown in the top menu. Press and hold left Alt to see menu hotkeys.
