### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Globalfirestorm10** [Klocman/Bulk-Crap-Uninstaller#519]
Hey devs, I just have a quick question:

Whenever I start up BCuninstaller, Bitdefender gives me a notification saying that the following link was blocked from opening via BCuninstaller:
http://bugsklocman.ddns.net:7721/GetAverageRatingsComp

any idea what this link is? I checked Virustotal, and it was marked 9 times as malicious, so I definitely won't be visiting it, but I just want to know if it's your site or not

**Comment by Klocman** [comment]
It's not malicious it's my server for user stats <https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/109ae7a9fd6b4bc6660c93b23faf0220a99b7f52/source/BulkCrapUninstaller/Functions/Ratings/UninstallerRatingManager.cs#L44>

**Comment by ArandomHitman** [comment]
Hey, Firestorms new account here, thanks for your response @Klocman. You should consider reaching out to the following AV companies about false positives so they don't mark your website as malicious:
Bitdefender
Avira
Cluster25
Sangfor
Sophos
VIPRE
and AlphaSOC (full report at https://www.virustotal.com/gui/url/4d8bf5eb6d25ccf74a5411e54d139750b16ea14b14e1f53db545e98db8fd210b/detection)
Thank you for making this wonderful program, it's saved my computer quite a few times. 
All the best :)

**Comment by Klocman** [comment]
You can never make all AV vendors happy, I have no idea what they think is malicious in this (if you enter the link you can see it's just plain text). I'd rather not have to find each and every one of their contact details to send a complaint and spend my time fixing bugs or doing anything else.

If anyone has time to spare to do this I'd be grateful though.

**Comment by Globalfirestorm10** [comment]
ill do it for Bitdefender, as I use their service. The rest of them though I can't guarantee
