### ISSUE TITLE
Make automatic updates optional during install

### ISSUE THREAD

**Issue by Klocman** [Klocman/Bulk-Crap-Uninstaller#52]

**Comment by vedantmgoyal2009** [comment]
@Klocman is this still relevant? 
* https://github.com/Klocman/Bulk-Crap-Uninstaller/issues/416
* https://github.com/Klocman/Bulk-Crap-Uninstaller/issues/404
* https://github.com/Klocman/Bulk-Crap-Uninstaller/pull/455

**Comment by Klocman** [comment]
It's no longer relevant, thanks for pointing it out.
