### ISSUE TITLE
Missing translation in overview box

### ISSUE THREAD

**Issue by NekoJonez** [Klocman/Bulk-Crap-Uninstaller#527]
While bulk uninstalling programs, in the overview dialog box the "Shutdown PC when..." checkbox isn't translated to Dutch. 
Most likely, there is a string missing in a language file... This could easily be fixed by adding the translation string in the correct file and translating it...

But, this raises another question. How are we going to make it easy for translators to contribute translations. Apps like WordPress like apps like GlotPress or translate.wordpress.org.... Maybe it's an idea to look into translation platforms to be set up or use something like CrowdIn to easy keep translations up-to-date and not have missing strings in languages so people have to make a hunt where to add it? Just food for tought. ;)

**Comment by Klocman** [comment]
Translating, including finding missing translations is very easy. Download the localization pack attached to the latest release and follow instructions inside.
