### ISSUE TITLE
Is it possible to unistall Micrsoft Edge?

### ISSUE THREAD

**Issue by JVenMax** [Klocman/Bulk-Crap-Uninstaller#533]
Hi.

I am learning here..

I tried to unistall Microsoft Edge but BCU failed..

Any idea?

Thanks in advance..

**Comment by Klocman** [comment]
Microsoft made it much more difficult to do this, it's honestly best to not bother and just hide it. If you really want to remove it, check one of the guides floating online, e.g. https://helpdeskgeek.com/windows-11/how-to-uninstall-microsoft-edge-from-your-windows-11-pc

**Comment by JVenMax** [comment]
Hi.Thanks a lot for your answer..
Sure, it seems you are right:
I uninstalled it with some pretty decent software that is capable of
removing stubborn programs (BCUninstaller - it's free) and guess what?
-> MS Windows reinstalled it by itself!!

So I had already decided to do exactly as you are suggesting here...
What could go wrong anyway..We are surrounded!! lol..
Thanks again!
Rgrds

**Comment by Klocman** [comment]
Yeah, it is what it is. At this point removing it can break some things as well so I just hide it. I'll close the issue in this case.
