### ISSUE TITLE
UI issue in the settings when a translation is longer than the box.

### ISSUE THREAD

**Issue by NekoJonez** [Klocman/Bulk-Crap-Uninstaller#541]
In the Dutch version of BCU, I noticed this in the settings: 
![image](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/4569581/9aeb6d41-513a-4e24-969c-bb405eeaa5f7)

So, as soon as a translation is longer then the original, the settings panel doesn't adjust for that. It simply let's it go over... I noticed this issue in the uninstall tab, yet in the detection tab when notice that there is a word wrap.

I also noticed this one in the interface tab:

![image](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/4569581/08e1bf56-5c9b-4b33-9e73-04f8e4143eda)

(PS: I'm looking into why there some untranslated strings in that tab.)

**Comment by Klocman** [comment]
It's a limitation of winforms, the text has to be split into multiple lines in the translation to fit (if using resxtranslatior, press shift+enter).

**Comment by NekoJonez** [comment]
The new language improvement PR should also fix this issue too for Dutch users.

**Comment by Klocman** [comment]
Since the fix PR is now merged I'll close this issue.
