### ISSUE TITLE
avira prime can't uninstall

### ISSUE THREAD

**Issue by anonysubscribe** [Klocman/Bulk-Crap-Uninstaller#545]
Dear BCU
I could not uninstall Avira prime 90 day free trail. I knocked out my windscribe VPN and rendered brave inoperable with windscribe, and even by itself, even after disabling brave site by site in search. BCU unistalls it but it still remains. a new utility pops up in uninstal avira.spotlight. ... But I can't kill it or all of them.

**Comment by Klocman** [comment]
Try uninstalling it in safe mode. There should also be an official Avira uninstall utility on their website.

**Comment by anonysubscribe** [comment]
Dear Mr Marcin

dell reset my windows and that should have fixed it.

thank you.

cando

On 20-10-2023 09:34 AM, Marcin Szeniak wrote:

> Try uninstalling it in safe mode. There should also be an official 
> Avira uninstall utility on their website. --Reply to this email 
> directly, view it on GitHub, or unsubscribe.You are receiving this bec
> 
> DuckDuckGo removed one tracker. More [1]
> 
> Report Spam [2]
> 
> Try uninstalling it in safe mode. There should also be an official 
> Avira uninstall utility on their website.
> 
> --
> Reply to this email directly, view it on GitHub [3], or unsubscribe 
> [4].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>

-- 
NULL

Links:
------
[1] 
https://duckduckgo.com/-omA2L5Il_qGIJI5lS2OdvymOOngH8EJQi3ZtHp6nvp3LQzbCnA5vlp5UFJnz3n_2aiYWQ9T2WsbQH1rY1FmO3n824LHdipznEAXiY8E-eyttNPIyOxnriEY87rX-_-LThq2sZTD4nn-eteBTBgkgpEUh0S16MMV8JmQ0C0igP39Y4girBxb9eMLpkC-ZU5cIBU5h4frQqVao2YP1eaYGlosEs0Tz5g_dF-sgnMdmsZQ2xP57s8ry8fsDAHs4bdk_E4OmXJ4KKxTnZj6z2yUtNeeygllE-pQDmR4NHhSiyy3cANbvP2pBRGDxJbCoVUsR_EEwM3Eu93eHNOnARd6gDGE7GEl39WfYN_cxPROErlQM5nqvSI7lXY7gf_65zQhLvkEj_k9ldHCK5LKnYPrnGAu1tEWWe9-6ZVjo3VdBPoFlBSW_n9x9EGGat1rZU2Sa0gPsPU13NBgKlcu4s-kioNBUH9WgNFA7TaoHoz4k5ObvKTAbZhWAU
[2] 
https://duckduckgo.com/-omA2L5Il_qGIJI5lS2OdvymOOngH8EJQi3ZtHp6nvp3LQzbCnA5vlp5UFJnz3n_2aiYWQ9T2WsbQH1rY1FmO3n824LHdipznEAXiY8E-eyttNPIyOxnriEY87rX-_-LThq2sZTD4nn-eteBTBgkgpEUh0S16MMV8JmQ0C0igP39Y4girBxb9eMLpkC-ZU5cIBU5h4frQqVao2YP1eaYGlosEs0Tz5g_dF-sgnMdmsZQ2xP57s8ry8fsDAHs4bdk_E4OmXJ4KKxTnZj6z2yUtNeeygllE-pQDmR4NHhSiyy3cANbvP2pBRGDxJbCoVUsR_EEwM3Eu93eHNOnARd6gDGE7GEl39WfYN_cxPROErlQM5nqvSI7lXY7gf_65zQhLvkEj_k9ldHCK5LKnYPrnGAu1tEWWe9-6ZVjo3VdBPoFlBSW_n9x9EGGat1rZU2Sa0gPsPU13NBgKlcu4s-kioNBUH9WgNFA7TaoHoz4k5ObvKTAbZhWAU
[3] 
https://github.com/Klocman/Bulk-Crap-Uninstaller/issues/545#issuecomment-1771841344
[4]
