### ISSUE TITLE
In the middle of uninstalling 35 programs, my computer crashed 😨 || Is finding the remaining leftover files possible?

### ISSUE THREAD

**Issue by jbrown1597** [Klocman/Bulk-Crap-Uninstaller#546]
Had 34/35 programs uninstalled before it locked up.

Typically, after #35, it would've scanned my files & registry for leftovers.

Am I screwed?

**Comment by Klocman** [comment]
In that case BCU can't look for leftovers of the applications uninstalled before the system crash.

**Comment by goyalyashpal** [comment]
> Had 34/35 programs uninstalled before it locked up.
Typically, after # 35, it would've scanned my files & registry for leftovers.

ohhh my gooodness.....

maybe BCU can save the information it extracts from uninstallers in some file ?
