### ISSUE TITLE
Unable to uninstall Display Driver Uninstaller with BCUninstaller

### ISSUE THREAD

**Issue by umut-nb0** [Klocman/Bulk-Crap-Uninstaller#547]
Bulk Crap Uninstaller application cannot see the Display Driver Uninstaller program. So I can't uninstall the Display Driver Uninstaller program with BCUninstaller.
Please take care of this issue.

I downloaded DDU from the link below
`https://www.guru3d.com/download/display-driver-uninstaller-download/`

![resim](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/147916475/81d5ce14-f37e-435c-941e-4e6ad7dcb33c)

**Comment by Klocman** [comment]
If you didn't have to install the program then it's a portable version that won't be detected unless you put it together with other applications or go to settings and manually add the folder with your portable applications.
If it did get installed, make sure that it's not being filtered out.

**Comment by umut-nb0** [comment]
The downloaded file seems to be portable because I couldn't find it in the C folder.
