### ISSUE TITLE
Program cloning

### ISSUE THREAD

**Issue by H3NGRY** [Klocman/Bulk-Crap-Uninstaller#554]
I think it would be good if the program cloning feature was introduced.

**Comment by Klocman** [comment]
How exactly would that feature work?

**Comment by H3NGRY** [comment]
It can be used to install the same program more than once, sometimes to check if it works while cracking.
Sorry for the late reply.

**Comment by Klocman** [comment]
I have no plans to add anything like this at the moment, since it sounds like a massive can of worms. Every application can and will act differently. Some will be fine with being copied (in that case you can just copy the folder yourself), while some will break because of config or registry issues.
