### ISSUE TITLE
BCU n5.7 x64 privileges

### ISSUE THREAD

**Issue by dsi1** [Klocman/Bulk-Crap-Uninstaller#555]
I was unable to remove a MS folder item because it required trusted installer status to do so.  The popup should have a button to temporarily grant TI Exec privileges in situ to move forward.  
great app,
Best,
dsi1

**Comment by dsi1** [comment]
trying to submit the Ti comment

**Comment by Klocman** [comment]
Duplicate of #356
Your best bet is the walkaround of running BCU as a SYSTEM or TrustedInstaller.
