### ISSUE TITLE
Different number and version shown of Stellarium in BC

### ISSUE THREAD

**Issue by Corsair-63** [Klocman/Bulk-Crap-Uninstaller#573]
System.NullReferenceException
Object reference not set to an instance of an object.
   at UninstallTools.Uninstaller.UninstallManager.Rename(ApplicationUninstallerEntry entry, String newName)
   at BulkCrapUninstaller.Forms.MainWindow.RenameEntries(Object sender, EventArgs eventArgs)

I've uninstalled all versions of this software because it says that I've installed version 23.1 x86 and 23.3 x64.
installed again version 23.4 x64 and continues giving me the display version installed in BC of 23.1 x86.

when I tried to rename the entrance, it says to me that not posible and send a report of the issue.
![sshot-4](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/76228638/dcd0490a-6d95-411d-9aef-ea6fd45166e4)

**Comment by Klocman** [comment]
Go to settings > misc > clear caches. Then, reload uninstallers and see if the issue is resolved.

**Comment by Corsair-63** [comment]
Thanks, it worked, now removed (x86)
