### ISSUE TITLE
Manual Refresh Uninstaller or automatic Refresh after Uninstall causes BCUninstaller to shut down

### ISSUE THREAD

**Issue by TheFly4242** [Klocman/Bulk-Crap-Uninstaller#58]
Carrying out an uninstall or dong a manual Refresh of uninstallers causes BCUninstaller to shut down on completion of refresh at least on my pc both with Version 3.7 and 3.71. I have not seen this before. By the way there is no error message coming up during this process just an application shutdown.

Thanks for a great app. It is a must have in my arsenal of PC Tools. Better than paid for uninstallers.

**Comment by Klocman** [comment]
Can you check `%LOCALAPPDATA%\Microsoft\Windows\WER\ReportArchive` for any files starting with `AppCrash_BCUninstaller*`? If there are some, delete them all, crash BCU again, and upload here the new appcrash that appears.

**Comment by TheFly4242** [comment]
The is no ReportArchive Folder in WER folder. There is only an ERC Folder which contains a file called viewedids.resp.

**Comment by TheFly4242** [comment]
I found the right location at "C:\ProgramData\Microsoft\Windows\WER\ReportArchive" There are no files starting with AppCrash_BCUninstaller.

**Comment by Klocman** [comment]
I can't reproduce the issue. Can you try downloading a fresh version and run it from a different folder? Maybe something got corrupted.

**Comment by TheFly4242** [comment]
I found the right location at "C:\ProgramData\Microsoft\Windows\WER\ReportArchive" There are no files starting with AppCrash_BCUninstaller.

**Comment by TheFly4242** [comment]
I tried as you suggested in your email. I re-downloaded the Version 3.6.1 Portable version and extracted it in another directory. I set it up with settings as I have before and after the initial loading of uninstallers, I then refreshed the uninstallers and again just as the progress reached the end the application disappeared with no message or dialogue. Maybe it is one of the settings I use that triggers this behaviour. I attach my BCUninstaller.settings file in the hope that you find something there or at least replicate this unusual behaviour.
Good Luck.
[BCUninstaller.settings.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/762673/BCUninstaller.settings.zip)

**Comment by Klocman** [comment]
Can you try disabling user ratings and usage statistics under `Settings>Misc`?

**Comment by TheFly4242** [comment]
Hi, I did as you suggested and disabled those settings. Closed BCU before starting it again and Refreshing and again it just disappeared as it got to the the end. But once before I got this Error which I pasted and copied. But did not get it on the last one with the settings above disabled.  Sorry for this trouble. I will try turning off some of the additional settings I set one by one to see if any of these trigger the BCU shutdown.

[Error.txt](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/768001/Error.txt)

**Comment by TheFly4242** [comment]
Actually, I created a new folder and extracted BCU into that and ran it. I accepted every default setting and then refreshed uninstallers and again when it reached the end it closed itself. So it must be something strange about my system and not my settings.

**Comment by Klocman** [comment]
Can you try creating a new user account, and running BCU on it? Maybe some other application is interfering, or some .net settings are bad.

**Comment by TheFly4242** [comment]
Actually, I created a new folder and extracted BCU into that and ran it. I accepted every default setting and then refreshed uninstallers and again when it reached the end it closed itself. So it must be something strange about my system and not my settings.

**Comment by TheFly4242** [comment]
Sorry for the delay in replying. I used another user account on same pc with both Version 3.7.1 as well as the new Version 3.7.2 and both exhibited the same behaviour as before.

**Comment by Klocman** [comment]
Can you replace the executable of 3.7.2 with [this](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/777978/BCUninstaller.zip), and see if refreshing the list still closes BCU? (don't worry about the blank list)

**Comment by TheFly4242** [comment]
Hi Marcin,

  I replaced the executable with the one in the link. I got the attached errors on the first scan and the exact same ones on the renew. And again on the end of the renew the app closed itself.
 Cheers. The Fly.

Thanks in advance for all your hard work.
--------------------------------------------
On Thu, 16/2/17, Marcin Szeniak <notifications@github.com> wrote:

 Subject: Re: [Klocman/Bulk-Crap-Uninstaller] Manual Refresh Uninstaller or automatic Refresh after Uninstall causes BCUninstaller to shut down (#58)
 To: "Klocman/Bulk-Crap-Uninstaller" <Bulk-Crap-Uninstaller@noreply.github.com>
 Cc: "TheFly4242" <thefly42@yahoo.com.au>, "Author" <author@noreply.github.com>
 Received: Thursday, 16 February, 2017, 5:14 AM
 
 Can you replace the executable of
 3.7.2 with this,
 and see if refreshing the list still closes BCU? (don't
 worry about the blank list)
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
BCUninstaller, Version=3.7.2.34525, Culture=neutral, PublicKeyToken=null | MSIL | Microsoft Windows NT 6.2.9200.0 | 64bit
System.ComponentModel.Win32Exception
Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at UninstallTools.Factory.SteamFactory.StartProcessAndReadOutput(String filename, String args)
   at UninstallTools.Factory.SteamFactory.GetSteamInfo()
   at UninstallTools.Factory.SteamFactory.get_SteamLocation()
   at UninstallTools.Factory.PredefinedFactory.GetSteamUninstallerEntry()
   at UninstallTools.Factory.PredefinedFactory.GetUninstallerEntries()
   at UninstallTools.Factory.ApplicationUninstallerFactory.GetMiscUninstallerEntries()
BCUninstaller, Version=3.7.2.34525, Culture=neutral, PublicKeyToken=null | MSIL | Microsoft Windows NT 6.2.9200.0 | 64bit
System.ComponentModel.Win32Exception
Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at UninstallTools.Factory.SteamFactory.StartProcessAndReadOutput(String filename, String args)
   at UninstallTools.Factory.StoreAppFactory.<GetUninstallerEntries>d__2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at UninstallTools.Factory.ApplicationUninstallerFactory.GetMiscUninstallerEntries()

**Comment by TheFly4242** [comment]
For your information the application disappears just after it displays the dialog "Populating installer list".

**Comment by Klocman** [comment]
I'm still having trouble replicating the problem, or finding anything that could cause it.

Do you happen to run any antiviruses or automation programs (like AutoIt)? If yes, what happens when you disable them?

**Comment by TheFly4242** [comment]
Hi,
   I don't have any Automation Software installed. As for Anti-Virus, I have Comodo Firewall, Panda Free Antivirus, Malwarebytes Free, SUPERAntiSpyware Free Edition and SpyBot and Destroy. I disabled all of these and BC Uninstaller Ver 3.7.2 still does the same thing. When the dialog that says "Populating installer list" reaches 100% the application just disappears.

Cheers.
TheFly4242
--------------------------------------------
On Tue, 7/3/17, Marcin Szeniak <notifications@github.com> wrote:

 Subject: Re: [Klocman/Bulk-Crap-Uninstaller] Manual Refresh Uninstaller or automatic Refresh after Uninstall causes BCUninstaller to shut down (#58)
 To: "Klocman/Bulk-Crap-Uninstaller" <Bulk-Crap-Uninstaller@noreply.github.com>
 Cc: "TheFly4242" <thefly42@yahoo.com.au>, "Author" <author@noreply.github.com>
 Received: Tuesday, 7 March, 2017, 3:50 AM
 
 I'm still having trouble
 replicating the problem, or finding anything that could
 cause it.
 Do you happen to run any antiviruses or automation
 programs (like AutoIt)? If yes, what happens when you
 disable them?
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by TheFly4242** [comment]
May I add that this issue has stopped occurring since Version 3.12. Also BC Uninstaller loads much quicker from starting application.

**Comment by Klocman** [comment]
This is weird, nothing that I changed should have affected this. My best guess is that your compiled assembly store got corrupted or there was a bug in NET that got fixed in an update.
