### ISSUE TITLE
is there an interface to uninstall the BCUninstaller itself for update?

### ISSUE THREAD

**Issue by beef-potato** [Klocman/Bulk-Crap-Uninstaller#580]
I'm using bcuninstaller 5.5 portable, and recently it remind me to update, I download the newer vision but can find uninstall option in the old one? so how can I uninstall it? just delete the root folder?

![bcUninstaller](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/95594775/1d2385eb-34d0-43c4-84df-5cfb41b0b5f7)

thanks for your work!

**Comment by MartinNiederl** [comment]
This is a portable version that can also run on a USB stick, for example, and does not need to be uninstalled. It is sufficient to delete the folder.

**Comment by beef-potato** [comment]
thank you
