### ISSUE TITLE
bloadware list 

### ISSUE THREAD

**Issue by Abane-S** [Klocman/Bulk-Crap-Uninstaller#585]
It will be cool if bdu would have bloadware list It will be cool if bcu would have a list to check with all the bloadware depending on the brand of the pc

**Comment by Klocman** [comment]
I don't really have the means to do it. There is a discussion about this matter [here](https://github.com/Klocman/Bulk-Crap-Uninstaller/discussions/530).

Currently your best bet are user ratings, but never trust those blindly and research the application if in doubt.
