### ISSUE TITLE
Edge browser not in the list

### ISSUE THREAD

**Issue by 7eptem** [Klocman/Bulk-Crap-Uninstaller#586]
microsoft edge browser not showing in the list

![edge](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/24566404/070fd67e-a883-4907-b46f-f1e78c4aa623)

**Comment by Klocman** [comment]
Check "show system components" and "show protected items" to see Edge.

**Comment by Popy64230** [comment]
J'ai beau respecter toutes les instructions pas moyen de voir disparaître "Edge" sans compter de fréquentes erreurs (1627) avec les trucs Microsoft que l'on veux supprimer
