### ISSUE TITLE
File size incorrectly estimated

### ISSUE THREAD

**Issue by beef-potato** [Klocman/Bulk-Crap-Uninstaller#589]
I am using BCUninstaller_5.7_portable, when I check my disk with bcuninstaller, I happened to find that GAOMON Tablet in the c disk is over 62GB while actually it is 62MB.

## file message:

GAOMON Tablet | GAOMON | 16.0.0.157 | 2024/2/3 | 62.27 GB | HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\GAOMONTablet | Unknown | C:\Users\belli dura despicio\AppData\Roaming\GAOMONTablet\Uninstall.exe |  | 

![gaomon bc view](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/95594775/6fbc9cbd-0411-46aa-94fb-a8c26364a080)

![gaoman issue](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/95594775/b1b9f0d2-5a18-4adc-ad22-45c54d110f88)

## soft ware download path:
https://gaomon.cn/plus/list.php?tid=10&hao=1060PRO%288192%E7%BA%A7%E5%8E%8B%E6%84%9F%29&bie=%E9%A9%B1%E5%8A%A8&tong=Windows#pcb

**Comment by Klocman** [comment]
Select this application on the list and export to xml from the file menu. Please send the exported xml file here.

**Comment by beef-potato** [comment]
<?xml version="1.0" encoding="utf-8"?>
<ApplicationEntrySerializer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Items>
    <ApplicationUninstallerEntry>
      <DisplayName>GAOMON Tablet</DisplayName>
      <BundleProviderKey>00000000-0000-0000-0000-000000000000</BundleProviderKey>
      <DisplayIcon>C:\Users\belli dura despicio\AppData\Roaming\GAOMONTablet\GAOMONTablet.exe</DisplayIcon>
      <DisplayVersion>16.0.0.157</DisplayVersion>
      <EstimatedSize>65293243</EstimatedSize>
      <InstallDate>2024-02-03T17:39:24.4368126+08:00</InstallDate>
      <Is64Bit>X86</Is64Bit>
      <IsProtected>false</IsProtected>
      <IsRegistered>true</IsRegistered>
      <IsOrphaned>false</IsOrphaned>
      <IsUpdate>false</IsUpdate>
      <IsValid>true</IsValid>
      <IsWebBrowser>false</IsWebBrowser>
      <Publisher>GAOMON</Publisher>
      <RatingId>GAOMONTablet</RatingId>
      <RegistryKeyName>GAOMONTablet</RegistryKeyName>
      <RegistryPath>HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\GAOMONTablet</RegistryPath>
      <SystemComponent>false</SystemComponent>
      <UninstallerFullFilename>C:\Users\belli dura despicio\AppData\Roaming\GAOMONTablet\Uninstall.exe</UninstallerFullFilename>
      <UninstallerKind>Unknown</UninstallerKind>
      <UninstallerLocation>C:\Users\belli dura despicio\AppData\Roaming\GAOMONTablet</UninstallerLocation>
      <UninstallString>C:\Users\belli dura despicio\AppData\Roaming\GAOMONTablet\Uninstall.exe</UninstallString>
    </ApplicationUninstallerEntry>
  </Items>
</ApplicationEntrySerializer>

**Comment by Klocman** [comment]
The EstimatedSize registry key does indeed read 62GB. That's the size reported by the application installer and you should be able to see it in Programs & Features as 62GB as well. This isn't really a bug in BCU, but the application's own installer reporting wrong size to the system.
