### ISSUE TITLE
App crashes to desktop during initial scan

### ISSUE THREAD

**Issue by XC3N** [Klocman/Bulk-Crap-Uninstaller#592]
BCU always force closes during the initial scan, and this happens at various times. I usually get to see the UI for a split second and then the process is gone.

How can I go about finding logs to learn what is causing it?

Thanks!

**Comment by Klocman** [comment]
Make sure you are using the latest version. Check BCUninstaller.exe directory for the log file and any crash dump zip files. Send them if you find any.

**Comment by XC3N** [comment]
hey sorry for taking so long to reply. I have reinstalled windows and installed the latest BCU with the same results. Log file attached, no zip dumps.
[BCUninstaller.log](https://github.com/user-attachments/files/17542583/BCUninstaller.log)
