### ISSUE TITLE
How to suppress auto-update.

### ISSUE THREAD

**Issue by metaad** [Klocman/Bulk-Crap-Uninstaller#598]
This issues was already raised  #583 but it was closed without the resolution. We are looking for setting to be implemented silently and not in GUI.

While testing it was found that when old version v5.6 is installed and shortcut is launched. Below pop-up comes up.
![image](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/106653425/29e4b825-fc07-424c-bb53-e2074b360c09)

**We are looking for settings to be implemented silently**. Creating file BCUninstaller.settings in the install directory after installation and adding only values for suppressing check for updates does not work. It re-takes the other inputs and Image 2 appears wherein check for updates is enabled:
There are multiple inputs that are taken after launching shortcut and all the settings are stored in BCUninstaller.settings. **Can you please suggest minimum settings that are required in the file, so that we can add above setting for suppressing the update.**

**Image 1:**
![image](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/106653425/d62bdf43-7ff4-4a3e-b89d-bffca3f47735)

**Image 2:** 
![image](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/106653425/f275865f-ec8d-42ad-a030-47881ac41714)

**Comment by Klocman** [comment]
Either you have not set MiscFirstRun to False (if set to True, the settings file is ignored), or your our settings file is seen as corrupted and is reset. Check BCUninstaller.log on startup after editing the settings file for related errors.

**Comment by Klocman** [comment]
Any updates? Did you manage to make it work correctly? Latest versions of BCU have all of the network options turned off by default so it shouldn't be necessary any more, just delete the old .settings file.

**Comment by metaad** [comment]
Yes, we were able to manage the auto-update disable setting through BCUninstaller.settings. We did set MiscUserId to 0 and MiscFirstRun to False as suggested earlier. 

Thanks!!
