### ISSUE TITLE
[Feature request] Ability to export a list of names of installed applications

### ISSUE THREAD

**Issue by zwsren435** [Klocman/Bulk-Crap-Uninstaller#603]
BCU already has a comprehensive and highly-customizable list of installed applications, so it would be nice to have a feature that outputs a list of the applications that BCU is currently showing, to a .txt or .csv or something.

**Comment by Klocman** [comment]
Select all applications you want to export and either right click and use the copy to clipboard menu and only pick display name, or use File > Export and later process the data in Excel or similar.
