### ISSUE TITLE
Turkish Language Support 

### ISSUE THREAD

**Issue by Recoo28** [Klocman/Bulk-Crap-Uninstaller#606]
Hello, have a nice day.

I've been using your app for a long time, but in a simple way. Although there are many settings and many options in your application, I can't use it literally because my language is not enough. Please bring Turkish language support or offer me another solution. I know that there are many people who use Bcunistals in my country, I think you will not ignore us. I'm just passing on my thanks. Good luck.

**Comment by Klocman** [comment]
Hello!

Anyone can create and submit translations by following instructions [here](https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/master/CONTRIBUTING.md#how-to-help-translate). I don't know Turkish or anyone who speaks it so I won't be able to help myself.

**Comment by Klocman** [comment]
Unfortunately there are no videos or more specific guides, what part did you get stuck on?

**Comment by Recoo28** [comment]
I did something from the ResxTranslator program and found the languages, there is a Turkish language section on the top right, how can I transfer them directly to the program?
10 May 2024 Cum ÖS 7:31 tarihinde Marcin Szeniak ***@***.*** ***@***.***> > şunu yazdı:
Unfortunately there are no videos or more specific guides, what part did you get stuck on?

**Comment by Klocman** [comment]
You can't use the translations directly, BCU has to be recompiled from source with those translations added.
Just translate everything you can and send me the files and I can send you a build of BCU with them included.

**Comment by Recoo28** [comment]
I need to write and send the Turkish words in my own language to the ones in the "NoLanguageValue" section.
I'm so sorry to bother you,I need this.
BlueMail <https://bluemail.me> for Desktop uygulamasını edinin
Marcin Szeniak wrote:
You can't use the translations directly, BCU has to be recompiled from source with those translations added.
Just translate everything you can and send me the files and I can send you a build of BCU with them included.

**Comment by DogancanYr** [comment]
[Localisation_Pack_5.8.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/15296206/Localisation_Pack_5.8.zip)

**Comment by Klocman** [comment]
@DogancanYr Thank you for the translation update!

**Comment by fastfingertips** [comment]
https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/23fe74542d6b781a8bc3a6cf3574258779019715/source/BulkCrapUninstaller/Forms/Windows/MainWindow.resx#L1417-L1419
