### ISSUE TITLE
PROGRAM GONE ROGUE! Deletes all files in downloads directory, no questions asked!!

### ISSUE THREAD

**Issue by abcdefghijk1234567890** [Klocman/Bulk-Crap-Uninstaller#611]
wut r u ppl doin?! i jst dl'd ths prg frm yr repo nd it's completly wipd out my downloads folder!!! how is dis even posssible?? didnt ya test ur shiit b4 relasin'?! i didnt give u permishun 2 delete anythin, let alone my whole dlz folder!!! 

so here's th issue: yr prg deleted ma downloads w/o askin permission! how r ppl s'posed t trust ur code if u'r just goN delete everthin?! i'ma need an explnition on why dis happened nd a fix ASAP or imma hav 2 report this to github & get it removd frm th repo!!!

**Comment by kdejeqq** [comment]
Bru is very reliable and virus-free software.
If you had done something bad. It's your problem !!!!
You can complain to github that this crappy software is a virus. Except
that it is Open Source. If you're sure of what you're saying, show me some
photos.

**Comment by Klocman** [comment]
If something like that actually happened then give exact steps that led to the issue. Also, ideally don't use a burner account and intentionally bad English.

**Comment by kdejeqq** [comment]
> que font les gens ?! J'ai juste téléchargé ce prg de mon dépôt de l'année et il est complètement effacé de mon dossier de téléchargements !!! comment est-ce possible ?? tu n'as pas testé ta libération de merde b4 ?! je ne vous ai pas donné le droit de supprimer quoi que ce soit, encore moins tout mon dossier dlz !!!
> 
> alors voici le problème : votre prg a supprimé mes téléchargements sans demander la permission ! Comment les gens sont-ils censés faire confiance à votre code si vous allez simplement supprimer tout ?! J'ai besoin d'une explication sur pourquoi cela s'est produit et d'un correctif dès que possible ou je vais devoir signaler cela à github et le supprimer du dépôt !!!

Shht !!!

**Comment by renatocfrancisco** [comment]
> wut r u ppl doin?! i jst dl'd ths prg frm yr repo nd it's completly wipd out my downloads folder!!! how is dis even posssible?? didnt ya test ur shiit b4 relasin'?! i didnt give u permishun 2 delete anythin, let alone my whole dlz folder!!!
> 
> so here's th issue: yr prg deleted ma downloads w/o askin permission! how r ppl s'posed t trust ur code if u'r just goN delete everthin?! i'ma need an explnition on why dis happened nd a fix ASAP or imma hav 2 report this to github & get it removd frm th repo!!!

funniest sh*t ever 😆

**Comment by SitHubCommit** [comment]
It sounds like someone paid this kid a few bucks to slander this repo.

**Comment by Klocman** [comment]
I'll just close this since there's no actionable information.
