### ISSUE TITLE
too many clicks

### ISSUE THREAD

**Issue by Chrysanthemum536** [Klocman/Bulk-Crap-Uninstaller#618]
to uninstall you have to click
uninstall
continue
continue
begin uninstallation
(go through everything in the actual uninstaller)
close
search for leftovers

and each of the steps can take 1-5 seconds to load, and I have almost never made any other choices during these steps
please add an option to just do everything

**Comment by toczekmj** [comment]
Just use quiet uninstall when available? I think that what are you looking for.

**Comment by Klocman** [comment]
At the moment it's only possible to skip confirmations in console mode with the appropriate switch. It's done the way it is now for the exact reasons @MaxHasBeenUsed mentioned.
