### ISSUE TITLE
[Request] Remember monitor position

### ISSUE THREAD

**Issue by TristisOris** [Klocman/Bulk-Crap-Uninstaller#624]
It always launch at primary monitor. Would be great to remember window size (fullscreen, custom size) and monitor position.
portable v5.8

**Comment by Klocman** [comment]
Did you try the latest non-portable version? It should remember the position per-PC either way.

**Comment by TristisOris** [comment]
i don't know what changed, same v5.8 now remember position and size.

**Comment by Klocman** [comment]
So the issue is resolved?
