### ISSUE TITLE
Update to latest on Winget

### ISSUE THREAD

**Issue by tEctutoRIt** [Klocman/Bulk-Crap-Uninstaller#642]
The latest version of Bulk-Crap-Uninstaller [v5.8.1) is currently not available on Winget. Adding the latest version to Winget would be beneficial for Windows users who use this tool to manage their software.

Appreciate all the work done on Bulk-Crap-Uninstaller and hope this can be updated soon.

**Comment by sitiom** [comment]
I have manually created a PR for now:
- https://github.com/microsoft/winget-pkgs/pull/171036
