### ISSUE TITLE
Typo in translation?

### ISSUE THREAD

**Issue by NekoJonez** [Klocman/Bulk-Crap-Uninstaller#648]
https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/8fb10eb3621b9a1766f6c79d7817d57d984ae3c5/source/BulkCrapUninstaller/Forms/Wizards/FirstStartBox.nl.resx#L248

I'm working on some updated translations and I noticed this one... Is there an "i" too much?

**Comment by Klocman** [comment]
The typo is in source code so as far as translations go this is correct.
