### ISSUE TITLE
Not detecting leftover files in "C:\Users\<username>\AppData\Local\Temp"

### ISSUE THREAD

**Issue by the-tuner** [Klocman/Bulk-Crap-Uninstaller#656]
I tried it for the first time. It works quite okay, removing every file created by the uninstalled apps. However, the largest leftover folder in the following path (image) of the Roblox program was not detected. Why is this?
_![image](https://github.com/user-attachments/assets/caf6eafe-d795-4404-b1e2-91dd0167f615)_

**Comment by Klocman** [comment]
Windows Temp folders are not scanned since they are cleaned automatically anyways.
