### ISSUE TITLE
Automatic install of .Net 3.5 fails on Windows 10

### ISSUE THREAD

**Issue by WagnerGMD** [Klocman/Bulk-Crap-Uninstaller#73]
```
---------------------------
Installation
---------------------------
Runtime Error (at 29:206):

Internal Error : ExtractTemporaryFile: The file "" was not found.
---------------------------
```
Hello,

as you can see (and here with [the picture](http://nsa37.casimages.com/img/2017/05/15/170515035302306701.jpg)), I had met one trouble when I had try to install the software Bulk Crap Uninstaller_(BCU)_v3.8.3. The BCU can't terminate the installation because I imagine, it's something about the **.Net Framework**, right ?

To see clear, can you anwser to these questions :

- The BCU isn't yet design to support Windows 10 ? Perhaps in the near futur ?
-  Which [.Net Framework](https://msdn.microsoft.com/en-us/library/5a4x27ek.aspx) is required ? Only the v3.5 ? Any plan about the latest (like **.Net Framework_v4.7**) ?
-  The installer should invite me to install (or download) it ? I saw nothing like that... 
-  What do you think to add one little resume (instructions) to fix the trouble ?

It's just one suggestion but I believe, you can improve [your FAQ](http://klocmansoftware.weebly.com/). To give you one another example, you had only mentionned Windows 7. From my point of view, it won't be clear about the other Windows.

Right now, I think I got the .Net Framework_v4.6.

Kind regards.

**PS :** By the word FAQ, I refer to **Other notable features** (which you can also add one HTML ancre. I didn't find it and by usual, I rather to provide the direct link).
For the instructions, the few lines below will give you one little example (to start).
```
#### The .Net Framework is preinstalled (inside the .iso Windows 8 and 10).
####  The online way :
dism /online /Enable-Feature /FeatureName:NetFx3 /All /LimitAccess /Source:G:\WindowsTenIso\sources\sxs
dism /online /Enable-Feature /FeatureName:NetFx3 /All /LimitAccess /Source:G:\WindowsEightIso\sources\sxs
####  The offline way :
dism /image:E:\MountWim /Enable-Feature /FeatureName:NetFx3 /All /LimitAccess /Source:G:\WindowsTenIso\sources\sxs
dism /image:E:\MountWim /Enable-Feature /FeatureName:NetFx3 /All /LimitAccess /Source:G:\WindowsEightIso\sources\sxs
#### Another way via this command : "C:\Windows\System32\OptionalFeatures.exe"
```

**Comment by Klocman** [comment]
Hello!

It looks like it's just a problem with the installer, not BCU itself. You can download the portable version from [here](https://www.fosshub.com/Bulk-Crap-Uninstaller.html) instead.

BCU fully supports Windows 10, and requires .Net 3.5 which Windows 10 will offer to install automatically.

At the moment there is no FAQ, but I am definitely looking into making one.

**Comment by WagnerGMD** [comment]
Hello,

thank you @Klocman, now it's clear. I think you're probably right about the installer. Because it seem's to work fine (with the portable version like on [this picture](http://nsa37.casimages.com/img/2017/05/20/170520062644664622.jpg) or [this one](http://nsa38.casimages.com/img/2017/05/20/170520070317638140.png)).

After I had try again (to install BCU) and the trouble seem's to be gone. I didn't see another error.
