### ISSUE TITLE
Missed leftovers at Registry

### ISSUE THREAD

**Issue by DmitriyYukhanov** [Klocman/Bulk-Crap-Uninstaller#76]
Hey, I've installed, launched and uninstalled 3D Mark 2001 SE with all leftovers removal (including bad confidence ones).
Following missed leftovers were noticed:

Key:
HKEY_USERS\S-1-5-21-1278579218-726299998-186589410-1001\SOFTWARE\Classes\VirtualStore\MACHINE\SOFTWARE\Wow6432Node\MadOnion.com

Key:
HKEY_USERS\S-1-5-21-1278579218-726299998-186589410-1001\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store

Item name:
C:\Program Files (x86)\MadOnion.com\3DMark2001 SE\3DMark2001SE.exe

Key:
HKEY_USERS\S-1-5-21-1278579218-726299998-186589410-1001\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers

Item name:
C:\Program Files (x86)\MadOnion.com\3DMark2001 SE\3DMark2001SE.exe

Related to #29:

HKEY_USERS\S-1-5-21-1278579218-726299998-186589410-1001\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\UserAssist\{CEBFF5CD-ACE2-4F4F-9178-9926F41749EA}\Count

Item name:
{7P5N40RS-N0SO-4OSP-874N-P0S2R0O9SN8R}\ZnqBavba.pbz\3QZnex2001 FR\3QZnex2001FR.rkr

And

HKEY_USERS\S-1-5-21-1278579218-726299998-186589410-1001\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\UserAssist\{F4E57C4B-2036-45F0-A9AB-443BCFE33D9F}\Count

Item name:
P:\Hfref\Choyvp\Qrfxgbc\3QZnex2001 FR.yax

**Comment by Klocman** [comment]
Thanks for the reports! I'll look into these.
