### ISSUE TITLE
Can't delete leftovers for Facebook Gameroom

### ISSUE THREAD

**Issue by DmitriyYukhanov** [Klocman/Bulk-Crap-Uninstaller#77]
I've uninstalled Facebook Gameroom and tried to remove leftovers, but it doesn't work for some reason.\
Being at this stage:
![image](https://cloud.githubusercontent.com/assets/883587/26763962/501a4a1c-4966-11e7-9960-219d0289cda9.png)

I press "Delete selected", window "Waiting for process to exit" blinks for 1-3 ms and nothing happens next:
![image](https://cloud.githubusercontent.com/assets/883587/26763972/809eee86-4966-11e7-81c1-a2392ddc7a51.png)

**Comment by Klocman** [comment]
After the window blinks, what exactly happens? Are you back to the Leftover removal window and can press Delete again?

**Comment by DmitriyYukhanov** [comment]
Yes, exactly.
It just blinks and nothing happens next.

**Comment by Klocman** [comment]
Could you test this again if I sent you a debug version?

**Comment by DmitriyYukhanov** [comment]
Sure, I'll try to!

**Comment by Klocman** [comment]
Try this version: [Debug.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/1052556/Debug.zip)

It should be fixed, but if you still have problems, close BCU and send me the BCUninstaller.log file.

**Comment by DmitriyYukhanov** [comment]
I've just tried to reproduce the issue and looks like it doesn't happen anymore.
Instead, Facebook Gameroom doesn't uninstall at all looks like.

I Uninstall it, delete all found leftovers, everything looks fine, but it's not removing. It's still at the apps list and I can repeat while uninstallation procedure again and again and leftovers are found again, etc. 

Please let me know how can I help debug this issue and I'll be glad to help.
Here is a log file after few such uninstallations.
[BCUninstaller.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/1052593/BCUninstaller.zip)

**Comment by Klocman** [comment]
I installed Gameroom and found out a few things:
- It uses an unusual install location that BCU can't detect, which means BCU can't see if it's running before uninstalling it. It probably isn't worth trying to detect it, as it would require a lot of HDD grinding = longer load times.
- When uninstalling normally it launches itself for some reason, and the uninstall won't continue until you log-in.
- Quiet uninstall works perfectly, Gameroom is closed automatically and leftover removal completes without issues.

**Comment by DmitriyYukhanov** [comment]
I just tried to uninstall it quietly but it's still there, still doesn't uninstalls =\

**Comment by DmitriyYukhanov** [comment]
Oh, sorry, I did tried it on that debug version you've sent.
I re-installed latest release version and quiet uninstall worked perfectly fine!

**Comment by Klocman** [comment]
All right, thanks! I'm closing this as fixed, since the Kill dialog is fixed and there's not much else that can be done here.
