### ISSUE TITLE
BCU recognizes its own shortcuts as leftovers of removed softwares.

### ISSUE THREAD

**Issue by stctn** [Klocman/Bulk-Crap-Uninstaller#79]
Screenshots:
https://ibb.co/ca7WtQ
https://ibb.co/kfTt7k

**Comment by Klocman** [comment]
That's pretty funny :)

What kind of applications causes this to happen? Store apps? You can check on installed applications by using "Manual Uninstall", and then canceling (nothing is removed).

**Comment by stctn** [comment]
It seems like this issue is only in place for Windows 10 Store Apps. See below;

Google Chrome Manual Uninstall:
https://ibb.co/n6xbtQ

Windows 10 Store App Manual Uninstall:
https://ibb.co/hMJuf5

**Comment by Klocman** [comment]
I can't reproduce it on apps that I have installed, and Store doesn't work for me...

Can you select Keeper on the application list, click File>Export selection, and send the the created .xml file?

**Comment by stctn** [comment]
C:\Program Files\BCUninstaller

I, unfortunately, can't provide you with the file you want. I already uninstalled unwanted Windows Store apps. But here I'm providing you the export XML of Microsoft Solitaire Collection, which is also a Windows Store App:

https://ufile.io/cvim8

_Uninstall Manually_ option gives me this:
![capture2](https://user-images.githubusercontent.com/21353964/27706187-49ba71a8-5d19-11e7-9049-22b043ce21a5.PNG)

**Comment by Klocman** [comment]
Thank you, I think I see what the issue is. I'll work on this later, since I already released the 3.10
