### ISSUE TITLE
(Suggestion) Do not copy "Uninstall BCUninstaller" to Start Menu as a shortcut.

### ISSUE THREAD

**Issue by stctn** [Klocman/Bulk-Crap-Uninstaller#80]
Hello,

"Uninstall BCUninstaller" shows up *before* "BCUninstaller" in start menu search, so a careless type-and-enter might cause problems.

Since nowadays it is possible to remove every program from windows control center, it is not necessary to copy over the shortcuts of "Uninstall BCUninstaller". Actually, it is frustrating to see excessive shortcuts in my start menu.

I can just delete it, but not having it in the first place is always better. So, I suggest you to not copy over the "Uninstall BCUninstaller"s shortcuts.

Best wishes.

**Comment by stctn** [comment]
Or even better: Offer a checkmark in the installer to opt-out from copying this over.

**Comment by Klocman** [comment]
I've thought it over, and I don't think it's worth changing this. This is how most people expect installation to work, and to some extent it's hard-coded into InnoSetup so it would take some effort to change. (and to translate the new option)

Another thing is, BCU is a program uninstaller, but how do you uninstall it itself? Other than using different manager, the most obvious way is to use the shortcut.

**Comment by stctn** [comment]
Maybe I can look into this myself some time in the future and send you a pull request.

And regarding your last paragraph, you can use the Windows Control Panel as I stated in the OP. I have never used an unistall shortcut since the early days of Windows XP, I have always used the control panel instead.

**Comment by Klocman** [comment]
Got it, I'll merge the change if you do it.
